"""
Cascade (pneumatic) method spatial layout.

Takes the circuit data dict (with _role on each node, generated by
circuit_generator.methods.cascade) and fills in x/y positions for every
component using circuit_generator.grid_layout.Grid -- design in
docs/superpowers/specs/2026-07-16-cascade-grid-layout-design.md.

Two regions:
  A. Piston/valve (top): one column per cylinder letter -- cylinder and
     4/2 valve share a column, flanked by an OR/sig staircase per side.
  B. Logic (bottom): one Grid row per pressure/memory line, button+closure
     column on the left, memory column, PR confirmation sig staircase on
     the right.
"""

import json
import math

from circuit_generator.grid_layout import Grid
from circuit_generator.sprite_metrics import METRICS as _M, anchor_local_for_routing
from paths import get_base_dir

_CONFIG_PATH = get_base_dir() / "circuit_generator" / "cascade_layout_config.json"

# Must match astar_router.route_connection's _OFFSET (entry offset applied
# toward the target anchor) -- a PL anchor chosen closer than this to the
# PR pilot's X produces a tight/ugly path (near-zero jog then re-entry at
# the same offset). Copied from step_by_step_layout.py (same constant, same
# reason).
_PL_ANCHOR_MIN_MARGIN = 20

# Extra margin (on top of _PL_ANCHOR_MIN_MARGIN) for the PL -> sig.P
# connection in the memory PR confirmation staircase (Region B,
# confirm_row) -- _PL_ANCHOR_MIN_MARGIN alone left too little clearance for
# this specific case. Region A uses only the base margin; its geometry
# isn't as tight.
_CONFIRM_ROW_P_EXTRA_MARGIN = 150

# Staggers the target of mem.PL/A/B -> PL connections by memory index (px),
# growing rightward -- without this every memory targets the same anchor
# (src_x doesn't depend on which memory), stacking several non-crossing
# connections in the same column.
_MEM_PL_STAGGER = 60


def _build_role_maps(data: dict) -> dict:
    """Extracts the letter/index -> node_id maps from each node's _role."""
    role_map = {n["id"]: n.get("_role", "") for n in data["nodes"]}

    cyl_by_letter: dict[str, str] = {}
    v42_by_letter: dict[str, str] = {}
    pl_by_idx: dict[int, str] = {}
    mc_by_idx: dict[int, str] = {}
    btn_id: str | None = None

    for nid, role in role_map.items():
        if role.startswith("cylinder:"):
            cyl_by_letter[role.split(":", 1)[1]] = nid
        elif role.startswith("main_valve:"):
            v42_by_letter[role.split(":", 1)[1]] = nid
        elif role.startswith("pressure_line_group:"):
            pl_by_idx[int(role.split(":", 1)[1])] = nid
        elif role.startswith("memory:"):
            mc_by_idx[int(role.split(":", 1)[1])] = nid
        elif role == "button":
            btn_id = nid

    return {
        "role_map":      role_map,
        "cyl_by_letter": cyl_by_letter,
        "v42_by_letter": v42_by_letter,
        "pl_by_idx":     pl_by_idx,
        "mc_by_idx":     mc_by_idx,
        "btn_id":        btn_id,
        "n_groups":      len(pl_by_idx),
        "n_mc":          len(mc_by_idx),
    }


def _build_trigger_sources(data: dict, roles: dict) -> dict[tuple[str, str], list[list[str]]]:
    """Reconstructs, from the connections list, the trigger sources feeding
    each pilot (letter, side) -- same idea as layout_engine.py's
    sig_to_v42/sig_to_or, generalized to return the full sig chain of each
    source (not just the sig id nearest the pilot), in the order cascade.py
    chains them (farthest from the cylinder first, matching `sources` in
    cascade.py section 6b).

    Key: (letter, side) where side is "PL" or "PR". Value: ordered list of
    leaves (farthest from the cylinder first); each leaf is a list of
    Valve_3_2_Ways ids from the root (P fed by a PressureLine) to the one
    nearest the pilot -- [] means a raw source (PressureLine feeding the
    pilot or OrValve directly, no sig in between).
    """
    role_map = roles["role_map"]
    node_type_map = {n["id"]: n["type"] for n in data["nodes"]}

    # sig.A -> (target type, target id, target anchor)
    sig_out: dict[str, tuple[str, str, str]] = {}
    # sig.P <- source (type, id) -- "PressureLine" or "Valve_3_2_Ways"
    sig_in: dict[str, tuple[str, str]] = {}

    for conn in data["connections"]:
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]
        s_type, t_type = node_type_map.get(s_id, ""), node_type_map.get(t_id, "")

        if s_type == "Valve_3_2_Ways" and s_anc == "A" and role_map.get(s_id, "").startswith("signal_valve:"):
            sig_out[s_id] = (t_type, t_id, t_anc)

        if t_type == "Valve_3_2_Ways" and t_anc == "P" and role_map.get(t_id, "").startswith("signal_valve:"):
            sig_in[t_id] = (s_type, s_id)

    def _walk_chain_to_leaf(sig_id: str) -> list[str]:
        """Walks up the sig.P <- sig.A chain from sig_id (which already
        feeds the pilot/OrValve) to find the root (P fed by a
        PressureLine) -- returns the chain from ROOT to sig_id (farthest
        -> nearest, matching how cascade.py builds it via
        prev_output)."""
        chain = [sig_id]
        current = sig_id
        while True:
            src_type, src_id = sig_in.get(current, (None, None))
            if src_type == "Valve_3_2_Ways":
                chain.insert(0, src_id)
                current = src_id
            else:
                return chain  # src_type == "PressureLine" (or not found)

    # Entry points into a pilot or OrValve: sig.A -> v42.PL/PR directly
    # (single source), sig.A -> OrValve.X/Y (2+ sources), or PL ->
    # OrValve.X/Y directly (a raw source feeding the OrValve with no sig).
    or_leaf_ids: dict[str, list[str]] = {}  # or_id -> [leaf sig_id above it, X then Y]
    or_role_of: dict[str, str] = {}

    for n in data["nodes"]:
        if n["type"] == "OrValve":
            or_role_of[n["id"]] = n.get("_role", role_map.get(n["id"], ""))

    for conn in data["connections"]:
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]
        s_type, t_type = node_type_map.get(s_id, ""), node_type_map.get(t_id, "")
        if t_type == "OrValve" and t_anc in ("X", "Y"):
            or_leaf_ids.setdefault(t_id, [None, None])
            slot = 0 if t_anc == "X" else 1
            if s_type == "Valve_3_2_Ways":
                or_leaf_ids[t_id][slot] = _walk_chain_to_leaf(s_id)
            else:
                or_leaf_ids[t_id][slot] = []  # raw source (PressureLine)

    sources: dict[tuple[str, str], list[list[str]]] = {}

    for letter, v42_id in roles["v42_by_letter"].items():
        for pilot_anc, side in (("PL", "PL"), ("PR", "PR")):
            # Case 1: sig.A -> v42.pilot directly (single source, no OrValve)
            direct_sig = next((sid for sid, (tt, tid, ta) in sig_out.items()
                                if tt == "Valve_4_2_Ways" and tid == v42_id and ta == pilot_anc), None)
            if direct_sig is not None:
                sources[(letter, side)] = [_walk_chain_to_leaf(direct_sig)]
                continue

            # Case 2: v42.pilot -> PL directly (single raw source).
            # cascade.py section 6b (line 352) builds this connection with
            # the 4/2 valve as "source" and the bus as "target" (not the
            # other way around) -- confirmed by reading
            # circuit_generator/methods/cascade.py and by generating
            # cascade.generate(parse("A+B+A-B-"))["connections"] directly:
            # it contains "gen-v42-A.PL -> gen-pl-grp1.X2", never the
            # reverse.
            has_direct_pl = any(
                c["source"]["node"] == v42_id and c["source"]["anchor"] == pilot_anc
                and node_type_map.get(c["target"]["node"]) == "PressureLine"
                for c in data["connections"]
            )
            if has_direct_pl:
                sources[(letter, side)] = [[]]
                continue

            # Case 3: OrValve chain -- find the final OrValve (the one
            # feeding the pilot directly) and unwind the binary chain
            # backward, in the same creation order as cascade.py section
            # 6b (sources[0] is the farthest).
            final_or = next((c["source"]["node"] for c in data["connections"]
                              if c["target"]["node"] == v42_id and c["target"]["anchor"] == pilot_anc
                              and node_type_map.get(c["source"]["node"]) == "OrValve"), None)
            if final_or is None:
                continue  # this side never fires in this sequence

            chain_or_ids = sorted(
                (oid for oid, role in or_role_of.items()
                 if role.startswith(f"or_valve:{letter}:{side}:")),
                key=lambda oid: int(or_role_of[oid].rsplit(":", 1)[1]),
            )
            leaves: list[list[str]] = []
            for i, or_id in enumerate(chain_or_ids):
                x_leaf, y_leaf = or_leaf_ids.get(or_id, [[], []])
                if i == 0:
                    leaves.append(x_leaf if x_leaf is not None else [])
                leaves.append(y_leaf if y_leaf is not None else [])
            sources[(letter, side)] = leaves

    return sources


def _logic_cell_width() -> float:
    cfg = json.loads(_CONFIG_PATH.read_text(encoding="utf-8"))
    return cfg["columns"]["logic_cell_width"]


def _walk_chain_to_leaf_generic(sig_in: dict, sig_id: str) -> list[str]:
    """Same logic as _walk_chain_to_leaf (Task 2), factored out for
    reuse here -- walks sig.P <- sig.A up to the root fed by a
    PressureLine."""
    chain = [sig_id]
    current = sig_id
    while True:
        src_type, src_id = sig_in.get(current, (None, None))
        if src_type == "Valve_3_2_Ways":
            chain.insert(0, src_id)
            current = src_id
        else:
            return chain


def apply(data: dict) -> dict:
    cfg  = json.loads(_CONFIG_PATH.read_text(encoding="utf-8"))
    cols = cfg["columns"]
    rows = cfg["rows"]

    roles = _build_role_maps(data)
    node_by_id = {n["id"]: n for n in data["nodes"]}
    sources = _build_trigger_sources(data, roles)

    grid = Grid()
    _reserved_cols: dict[str, set[int]] = {}

    def _place_aligned(row_id: str, virtual_col: int, node_id: str) -> tuple[float, float]:
        """Like grid.place, but guarantees virtual_col lands at arrival
        index `virtual_col` in the row (reserving columns
        0..virtual_col-1 with placeholder occupants if not already used),
        so skipped columns stay aligned in X across different rows."""
        reserved = _reserved_cols.setdefault(row_id, set())
        for kk in range(virtual_col):
            if kk not in reserved:
                grid.place(row_id, kk, f"__reserved__{row_id}__{kk}__")
                reserved.add(kk)
        reserved.add(virtual_col)
        return grid.place(row_id, virtual_col, node_id)

    # -- Width of each side (number of columns = number of leaves, N) ------
    def _side_width(letter: str, side: str) -> int:
        leaves = sources.get((letter, side), [])
        return len(leaves)  # N leaves -> N columns (see Task 3's formula)

    letters = sorted(roles["cyl_by_letter"])
    cyl_col: dict[str, int] = {}
    col = 0
    for letter in letters:
        col += _side_width(letter, "PL")
        cyl_col[letter] = col
        col += 1 + _side_width(letter, "PR")

    # Live-UI testing found that with cols["group_gap"] alone, two adjacent
    # sigs in neighboring columns (e.g. one cylinder's PR and the next one's
    # PL) could visually overlap -- the clearance (group_gap - sig sprite
    # width) didn't cover the worst case where the left sig is commutated
    # (BODY_VISUALS[1] shifts the ENTIRE body, including actuators,
    # +pilot_side_offset_x to the right -- see sig_col_pitch in
    # sprite_metrics.py). Uses the larger of the configured value and the
    # minimum pitch that guarantees no overlap in that worst case.
    cyl_cell_w = max(cols["group_gap"], _M.sig_col_pitch)
    grid.add_row("cylinder",   cyl_cell_w, _M.cyl_height, rows["cylinder"],
                 x_origin=cols["cylinder_first_x"])
    grid.add_row("main_valve", cyl_cell_w, _M.v42_height, rows["main_valve"],
                 x_origin=cols["cylinder_first_x"])

    for letter in letters:
        cyl_id = roles["cyl_by_letter"][letter]
        v42_id = roles["v42_by_letter"][letter]
        x, y = _place_aligned("cylinder", cyl_col[letter], cyl_id)
        node_by_id[cyl_id]["position"] = {"x": x, "y": y}
        x, y = _place_aligned("main_valve", cyl_col[letter], v42_id)
        node_by_id[v42_id]["position"] = {"x": x, "y": y}

    # -- Virtual columns for each leaf/OrValve, by (letter, side) -----------
    #
    #   N leaves -> columns at offset 1..N from cyl_col[letter] (sign
    #   flipped for the PL side). offset(leaf_j) = N-j for j>=1 (same
    #   column as OrValve or_i=j-1, stacked below it); offset(leaf_0) = N
    #   (one column past the farthest OrValve). offset(OrValve at or_i) =
    #   N-1-or_i (same formula already used by
    #   step_by_step_layout._or_valve_xy, reused unchanged).
    # (max chain length per (letter, side) is not tracked separately -- the
    # "same row height for both sides of a cylinder" requirement holds for
    # free below, since sig_stack_{depth} rows are keyed by depth alone and
    # shared across ALL letters/sides, not allocated per-cylinder.)
    leaf_virtual_col: dict[tuple[str, str, int], int] = {}   # (letter, side, j) -> offset
    or_virtual_col:   dict[str, int] = {}                    # or_id -> offset (absoluto, cyl_col +/- offset)

    for letter in letters:
        for side, sign in (("PL", -1), ("PR", 1)):
            leaves = sources.get((letter, side), [])
            n = len(leaves)
            for j, leaf in enumerate(leaves):
                offset = n if j == 0 else (n - j)
                leaf_virtual_col[(letter, side, j)] = offset
            if n >= 2:
                for or_i in range(n - 1):
                    or_offset = n - 1 - or_i
                    role_prefix = f"or_valve:{letter}:{side}:{or_i}"
                    or_id = next(nid for nid, node in node_by_id.items()
                                 if node.get("_role", "") == role_prefix)
                    or_virtual_col[or_id] = cyl_col[letter] + sign * or_offset

    # -- Position OrValve (own row, same height for both sides) ----------
    if or_virtual_col:
        min_vcol = min(or_virtual_col.values())
        grid.add_row("or_row", cyl_cell_w, _M.or_height, rows["or_row"],
                     x_origin=cols["cylinder_first_x"] + min_vcol * cyl_cell_w)
        for or_id in sorted(or_virtual_col, key=lambda k: or_virtual_col[k]):
            vcol = or_virtual_col[or_id]
            x, y = _place_aligned("or_row", vcol - min_vcol, or_id)
            node_by_id[or_id]["position"] = {"x": x, "y": y}

    # -- Position each leaf's sig chain (0+ stacked rows) -------------------
    #
    # IMPORTANT: _place_aligned assumes that, for a given row_id, calls
    # arrive in ASCENDING virtual_col order (it pre-reserves placeholders
    # for columns 0..virtual_col-1 not yet used). The leaf loop iterates
    # j = 0, 1, 2..., but for the PR side (sign=+1) the corresponding vcol
    # DESCENDS in j (offset = n at j==0, then n-j) -- calling _place_aligned
    # in iteration order would break that precondition and collide with a
    # placeholder already reserved by an earlier, larger-vcol call
    # (ValueError). So we first collect all placements (by row_id), then
    # call _place_aligned in ascending vcol order within each row_id --
    # same strategy already used above for or_row (sorted(or_virtual_col,
    # key=...)), generalized here so it doesn't need to know in advance
    # which side needs reversing.
    sig_stack_row_ids_created: set[str] = set()  # tracks rows already created (Grid has no "already exists" check)
    # row_id -> list of (vcol, sig_id, depth)
    pending_by_row: dict[str, list[tuple[int, str, int]]] = {}
    for letter in letters:
        for side, sign in (("PL", -1), ("PR", 1)):
            leaves = sources.get((letter, side), [])
            for j, leaf in enumerate(leaves):
                if not leaf:
                    continue  # raw leaf -- no valve, no row
                offset = leaf_virtual_col[(letter, side, j)]
                vcol = cyl_col[letter] + sign * offset
                # `leaf` comes in root->tip order (leaf[0] = fed by the
                # PL, leaf[-1] = whose A feeds the pilot/OrValve). The tip
                # must sit CLOSER to the pilot/OrValve it feeds (lower y,
                # nearer or_row) -- the root, which only needs to reach the
                # PL (further down), sits farther (higher y). Without
                # reversed(), the order came out inverted: root on top, tip
                # at the bottom.
                for depth, sig_id in enumerate(reversed(leaf)):
                    row_id = f"sig_stack_{depth}"
                    pending_by_row.setdefault(row_id, []).append((vcol, sig_id, depth))

    for row_id in sorted(pending_by_row, key=lambda rid: int(rid.rsplit("_", 1)[1])):
        placements = pending_by_row[row_id]
        depth = placements[0][2]
        if row_id not in sig_stack_row_ids_created:
            # NOTE for Task 4/5: this row is GLOBAL (shared by ALL
            # cylinders/letters/sides in the circuit), not one row per
            # cylinder -- sig_stack_{depth} is keyed only by chain depth.
            # This gives "PL and PR of the SAME cylinder share the same row
            # height" as a side effect of the broader invariant "everyone
            # at the same depth shares the same row" (even across
            # different cylinders) -- not verified whether this global
            # sharing still holds once Region B (Tasks 4/5) is stacked on
            # top of these rows.
            grid.add_row(row_id, cyl_cell_w, _M.v32_height,
                         rows["or_row"] + (depth + 1) * _M.v32_height * 1.5,
                         x_origin=cols["cylinder_first_x"])
            sig_stack_row_ids_created.add(row_id)
        for vcol, sig_id, _depth in sorted(placements, key=lambda p: p[0]):
            x, y = _place_aligned(row_id, vcol, sig_id)
            node_by_id[sig_id]["position"] = {"x": x, "y": y}

    # -- Region B: pressure lines + memories (local rows 1..M) -----------
    n_groups = roles["n_groups"]
    n_mc     = roles["n_mc"]
    memory_x0 = cols["cylinder_first_x"]
    logic_cell_w = cols["logic_cell_width"]
    # NOTE (interface from Task 3's actual implementation, not the original
    # draft): Task 3 replaced a planned `max_rows_per_cyl` dict with
    # `sig_stack_row_ids_created`, a `set[str]` of the `sig_stack_{depth}`
    # row ids actually created (Region A's rows are global across all
    # cylinders, keyed only by depth -- see Task 3's code comments). Since
    # depths are always populated contiguously from 0, its length equals
    # the max chain depth reached anywhere in Region A -- use that here
    # instead of max_rows_per_cyl, which no longer exists.
    #
    # Live-UI testing found a real bug, fixed here: the original formula
    # only added `N * v32_height * 1.5` (the SPACING between sig_stack
    # rows) to the top of or_row, without adding the deepest row's own
    # body HEIGHT -- with N=2, the deepest sig_stack row ends at
    # `or_row + 2*v32_height*1.5 + v32_height`, but the old formula
    # started a PL one v32_height BEFORE that: a real sprite overlap (see
    # test_pl_rows_start_below_the_deepest_sig_stack_row). Fixed by
    # computing the real Y of Region A's bottom (or_row alone if N==0, or
    # the bottom of the deepest sig_stack if N>0) and preserving the same
    # margin `rows["pl_base"]` already gave for the N==0 case (the config
    # constant's meaning never changed, only the calculation of where
    # Region A actually ends).
    _region_a_margin = rows["pl_base"] - (rows["or_row"] + _M.or_height)
    if sig_stack_row_ids_created:
        _n_stack_rows = len(sig_stack_row_ids_created)
        _region_a_bottom = rows["or_row"] + _n_stack_rows * _M.v32_height * 1.5 + _M.v32_height
    else:
        _region_a_bottom = rows["or_row"] + _M.or_height
    pl_base_y = _region_a_bottom + _region_a_margin

    for g in range(n_groups):
        local_row = g + 1  # local row 1..M
        y = pl_base_y + (local_row - 1) * rows["pl_gap"]
        pl_id = roles["pl_by_idx"][g]
        grid.add_row(f"pl_row_{g}", 200, _M.pl_pix_h, y, x_origin=memory_x0)
        x, y2 = grid.place(f"pl_row_{g}", 0, pl_id)
        node_by_id[pl_id]["position"] = {"x": x, "y": y2}

    # Live-UI testing found a real bug, fixed here: the previous version
    # put mem[i] on the SAME row (same y) as the PL it drives via B --
    # since the PL renders as a thin horizontal bus at that exact height,
    # the memory's body (much taller, v52_height) literally sat ON TOP of
    # the PL's line, crossing the drawing. The logical mapping
    # mem[i] <-> pl_grp[n_groups-1-i] still holds (same relative order:
    # mem[n_mc-1] confirms the highest group, mem[0] the lowest), but the
    # whole memory block now sits BELOW ALL PL rows -- same pattern
    # already used by step_by_step_layout.py (the whole logic region below
    # the whole PL region, never interleaved row by row).
    memory_y_base = pl_base_y + n_groups * rows["pl_gap"] + rows["logic_row_gap"]
    for i in range(n_mc):
        mem_id = roles["mc_by_idx"][i]
        local_rank = n_mc - 1 - i  # 0 = highest memory (mem[n_mc-1])
        y = memory_y_base + local_rank * rows["pl_gap"]
        grid.add_row(f"memory_row_{i}", logic_cell_w, _M.v52_height, y, x_origin=memory_x0)
        x, y2 = grid.place(f"memory_row_{i}", 0, mem_id)
        node_by_id[mem_id]["position"] = {"x": x, "y": y2}

    # -- Button column (column 1, left of the memory column) -------------
    if n_mc:
        mc0_id = roles["mc_by_idx"][0]
        mc0_y  = node_by_id[mc0_id]["position"]["y"]
        btn_id = roles["btn_id"]
        btn_x0 = memory_x0 - logic_cell_w
        grid.add_row("btn_row", logic_cell_w, _M.v32_height,
                     mc0_y + rows["logic_row_gap"], x_origin=btn_x0)
        x, y = grid.place("btn_row", 0, btn_id)
        node_by_id[btn_id]["position"] = {"x": x, "y": y}

    # -- PR confirmation chains (mem[i].PR) and closure (btn.P) -----------
    node_type_map = {n["id"]: n["type"] for n in data["nodes"]}
    sig_in: dict[str, tuple[str, str]] = {}
    for conn in data["connections"]:
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]
        s_type, t_type = node_type_map.get(s_id, ""), node_type_map.get(t_id, "")
        if t_type == "Valve_3_2_Ways" and t_anc == "P":
            sig_in[t_id] = (s_type, s_id)

    def _chain_feeding(target_id: str, target_anchor: str) -> list[str]:
        head = next((c["source"]["node"] for c in data["connections"]
                     if c["target"]["node"] == target_id and c["target"]["anchor"] == target_anchor
                     and node_type_map.get(c["source"]["node"]) == "Valve_3_2_Ways"), None)
        return _walk_chain_to_leaf_generic(sig_in, head) if head else []

    # Local rows top to bottom: mem[-1] (n_mc-1) is the top (offset 0),
    # mem[0] is the bottom. btn.P (closure) is NOT part of this staircase
    # -- see the dedicated block below (same column as the button, not the
    # staircase to the right of the memories -- live-UI testing found the
    # previous version treated btn.P as just another "row" of the memory
    # confirmation staircase, pushing the closure chain far from the
    # button's column).
    ordered_targets = [(roles["mc_by_idx"][i], "PR") for i in range(n_mc - 1, -1, -1)]

    # mem_id -> x of the valve that directly drives that memory's PR (the
    # chain's last link, chain[-1] -- the rightmost in the staircase) --
    # used below to route mem[i].B (i != mem[-1], the highest) to just
    # left of that valve's sprite, instead of a generic stagger (per
    # live-UI feedback, with an attached drawing showing the expected
    # route).
    driving_sig_x_by_mem: dict[str, float] = {}

    offset = 0
    for target_id, target_anchor in ordered_targets:
        chain = _chain_feeding(target_id, target_anchor)
        if not chain:
            continue
        # Diagonal (one row below the memory it feeds), same rule
        # already used for the button/mem[0] pair -- confirmed with the
        # user (previously it sat on the SAME row as the memory).
        # rows["pl_gap"] needs to be >= logic_row_gap + v32_height so this
        # diagonal doesn't collide with the next memory down (see
        # cascade_layout_config.json).
        target_y = node_by_id[target_id]["position"]["y"] + rows["logic_row_gap"]
        row_id = f"confirm_row_{target_id}"
        grid.add_row(row_id, logic_cell_w, _M.v32_height, target_y, x_origin=memory_x0)
        # `chain` comes in root->tip order (chain[0] = fed by the PL,
        # chain[-1] = whose A feeds target_id.PR). The tip (which connects
        # to the memory) must sit CLOSER to the memory column (smaller
        # offset, further left) -- the root, which only needs to reach the
        # PL (farther away), sits further right. Without reversed(), the
        # order came out inverted: root next to the memory, tip far away.
        for k, sig_id in enumerate(reversed(chain)):
            x, y = _place_aligned(row_id, offset + 1 + k, sig_id)
            node_by_id[sig_id]["position"] = {"x": x, "y": y}
        offset += len(chain)
        driving_sig_x_by_mem[target_id] = node_by_id[chain[-1]]["position"]["x"]

    # -- Closure chain (btn.P): button's column, stacked below ------------
    #
    #   Same column as btn_x0 (not the memory column) -- matching
    #   btn_row/closure_row/closure_stack_N from the step-by-step method.
    #   The chain is walked back to front when positioning: the link
    #   closest to the button (whose A feeds btn.P) sits in the row right
    #   below it (depth 1); links farther away (closer to the root fed by
    #   the PL) sit even further down.
    closure_sig_ids: set[str] = set()
    if n_mc:
        closure_chain = _chain_feeding(btn_id, "P")
        if closure_chain:
            closure_sig_ids = set(closure_chain)
            closure_chain_top_down = list(reversed(closure_chain))
            btn_y = node_by_id[btn_id]["position"]["y"]
            for depth, sig_id in enumerate(closure_chain_top_down, start=1):
                row_id = f"closure_stack_{depth}"
                grid.add_row(row_id, logic_cell_w, _M.v32_height,
                             btn_y + depth * rows["logic_row_gap"], x_origin=btn_x0)
                x, y = grid.place(row_id, 0, sig_id)
                node_by_id[sig_id]["position"] = {"x": x, "y": y}

    node_pos = {nid: (n["position"]["x"], n["position"]["y"]) for nid, n in node_by_id.items()}
    pl_node_map = {pid: node_by_id[pid] for pid in roles["pl_by_idx"].values()}

    # sig_ids from Region A (leaves stacked right below or_row, see
    # Task 3) -- the ones feeding the 4/2's pilot (PL/PR) directly or via
    # OrValve. Live-UI testing (with an annotated screenshot showing the
    # expected route): the PL -> sig.P connection for these sigs must exit
    # to the RIGHT (down then right to the PressureLine), not to the
    # left.
    region_a_sig_ids = {sid for leaves in sources.values() for leaf in leaves for sid in leaf}

    # sig_ids that enter the PL -> sig.P connection from the LEFT: only
    # the closure chain (closure_sig_ids, button's column) -- direct user
    # feedback: this sig should keep entering from the left.
    left_entry_sig_ids = set(closure_sig_ids)

    # mem_id -> index i (inverted mc_by_idx) -- used below to stagger the
    # target of mem.PL/A/B -> PL connections per memory.
    mc_idx_by_id = {mid: i for i, mid in roles["mc_by_idx"].items()}

    # -- Sizes PressureLines from the grid's real reach ---------------------
    #
    #   Ported verbatim from step_by_step_layout.py (same block, same
    #   guiding comment) -- already generic over
    #   pl_node_map/grid.occupied_x_range, no substitution needed (see
    #   Task 6 brief, item 1).
    pl_row_ids = {f"pl_row_{g}" for g in roles["pl_by_idx"]}
    x_range = grid.occupied_x_range(exclude_rows=pl_row_ids)
    if x_range is not None:
        min_x, max_x = x_range
        reach_margin = cols["logic_cell_width"]
        left_margin = _M.pilot_w
        for pl_id, pl_node in pl_node_map.items():
            existing_idxs = [int(a[1:]) for a in pl_node["properties"]["anchors"]]
            needed_max = max(1, math.ceil(
                (max_x + reach_margin - pl_node["position"]["x"] - _M.pl_pix_w / 2) / _M.pl_spacing
            ) + 1)
            needed_min = math.floor(
                (min_x - left_margin - pl_node["position"]["x"] - _M.pl_pix_w / 2) / _M.pl_spacing
            ) + 1
            lo = min(needed_min, min(existing_idxs) if existing_idxs else 1)
            hi = max(needed_max, max(existing_idxs) if existing_idxs else 1)
            pl_node["properties"]["anchors"] = [f"X{i}" for i in range(lo, hi + 1)]
            if lo < 1:
                pl_node["position"]["x"] += (lo - 1) * _M.pl_spacing
                node_pos[pl_id] = (pl_node["position"]["x"], pl_node["position"]["y"])

    # -- PressureLine bus taps (RailPlanner) -----------------------------------
    #
    #   The topology generator assigns X1, X2, ... sequentially, with no
    #   notion of screen position -- this produces wires that
    #   unnecessarily cross the drawing. Requests a tap at the real X
    #   position of the component on the other side of the connection --
    #   shared as circuit_generator.rail.RailPlanner (generic, nothing
    #   Valve_5_2_Ways-specific), same as layout_engine.py/
    #   step_by_step_layout.py. Only the elif chain of connections_sorted
    #   below is cascade-specific, recognizing the cascade-specific
    #   PL/PR/A/B <-> PressureLine connection shapes (mc is
    #   Valve_5_2_Ways, step-by-step only has Valve_3_2_Ways).
    from circuit_generator.rail import RailPlanner

    rail = RailPlanner(min_spacing=_M.pl_spacing)
    for pl_id, pl_node in pl_node_map.items():
        rail.register_pressure_line_bus(pl_id, pl_node, node_pos[pl_id])

    # RailPlanner.request_tap replaces the old local `_resolve_conflict` --
    # collision/ordering resolution (per-bus AND the cross-row
    # "avoid_global_x" case) now lives in rail.py, shared across all 3
    # generators using this pattern.

    def _target_x(node_id: str, anchor_name: str) -> float:
        ntype = node_type_map.get(node_id, "")
        pos = node_by_id[node_id]["position"]
        local = anchor_local_for_routing(ntype, anchor_name)
        return pos["x"] + local[0] if local else pos["x"]

    def _conn_sort_key(c: dict) -> tuple:
        t_id = c["target"]["node"]
        return (0, 0) if t_id in pl_node_map else (1, 0)

    connections_sorted = sorted(
        [c for c in data["connections"] if c["source"]["node"] != c["target"]["node"]],
        key=_conn_sort_key,
    )

    for conn in connections_sorted:
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]

        if s_id in pl_node_map and s_anc.startswith("X"):
            tgt_x = _target_x(t_id, t_anc)
            avoid_global_x = False
            owner_id = f"{t_id}#{t_anc}" if node_type_map.get(t_id) == "OrValve" else t_id
            # desired_x bakes in the old "side" + min_margin search
            # (_nearest_pl_anchor's "left"/"right" + min_margin) directly
            # as a numeric offset from the target, since RailPlanner taps
            # at a continuous x rather than choosing among discrete named
            # anchors -- push_dir keeps re-pushing on collision in the
            # same direction that motivated the offset.
            if t_anc == "PL":
                desired_x = tgt_x
                push_dir = -1
            elif t_anc == "PR":
                desired_x = tgt_x + _PL_ANCHOR_MIN_MARGIN
                push_dir = 1
            elif t_anc == "P" and node_type_map.get(t_id) == "Valve_3_2_Ways" and t_id in left_entry_sig_ids:
                # Closure-chain sig (button's column, leftmost of
                # everything): enters from the left -- same logic
                # inherited from step-by-step (direct user feedback:
                # should keep entering from the left). This is the ONLY
                # exception -- both Region A (the OR/sig-staircase leaf
                # feeding the 4/2's pilot) and Region B (confirm_row, feeds
                # mem.PR) exit from the right, see branches below.
                valve_left_x = node_by_id[t_id]["position"]["x"]
                desired_x = valve_left_x - _M.pilot_w
                push_dir = -1
                avoid_global_x = True
            elif t_anc == "P" and node_type_map.get(t_id) == "Valve_3_2_Ways" and t_id in region_a_sig_ids:
                # Region A (the OR/sig-staircase leaf feeding the 4/2's
                # pilot directly or via OrValve): exits to the RIGHT
                # (found via live-UI testing, with an annotated screenshot
                # showing the expected route: exits right, then goes up to
                # the nearest anchor on the right). Only the BASE margin
                # (_PL_ANCHOR_MIN_MARGIN) -- without confirm_row's extra
                # margin below, which has no obstacle justifying it here.
                desired_x = tgt_x + _PL_ANCHOR_MIN_MARGIN
                push_dir = 1
                avoid_global_x = True
            elif t_anc == "P" and node_type_map.get(t_id) == "Valve_3_2_Ways":
                # Region B (confirm_row, feeds mem.PR): exits to the RIGHT
                # (found via live-UI testing, with an annotated screenshot
                # showing the expected route: exits right, then goes up to
                # the nearest anchor on the right). `tgt_x` (computed above
                # via _target_x -> anchor_local_for_routing) is already the
                # worst-case value adjusted for the commutation shift (same
                # fix as anchor_local_for_routing("Valve_3_2_Ways","P") in
                # sprite_metrics.py) -- using a different safe_x here (e.g.
                # based only on v32_width+pilot_w) would aim the router at
                # a point FARTHER RIGHT than the real endpoint (always
                # tgt_x), forcing the trace back left on the final stretch
                # -- exactly the zigzag this fix is meant to eliminate, not
                # create. Extra margin (_CONFIRM_ROW_P_EXTRA_MARGIN): the
                # default margin alone still left too little clearance
                # specifically here (per live-UI feedback) -- unlike
                # Region A above, which doesn't need this extra clearance.
                desired_x = tgt_x + _PL_ANCHOR_MIN_MARGIN + _CONFIRM_ROW_P_EXTRA_MARGIN
                push_dir = 1
                avoid_global_x = True
            elif t_anc == "X" and node_type_map.get(t_id) == "OrValve":
                desired_x = tgt_x - _PL_ANCHOR_MIN_MARGIN
                push_dir = -1
                avoid_global_x = True
            elif t_anc == "Y" and node_type_map.get(t_id) == "OrValve":
                desired_x = tgt_x + _PL_ANCHOR_MIN_MARGIN
                push_dir = 1
                avoid_global_x = True
            # -- Cascade-specific shapes: Valve_5_2_Ways (memory) PL/PR/A/B
            #   fed DIRECTLY by a PressureLine (no sig in between) --
            #   step_by_step_layout.py never has this shape because its
            #   memories are Valve_3_2_Ways, and the only "PL as source"
            #   case for them is P (already covered above). Verified by
            #   running cascade.generate() on several real sequences (see
            #   Task 6 report): the current generator NEVER produces a
            #   PressureLine as the source of a mem.PL/PR/A/B connection --
            #   those connections always come from a memory or a sig (the
            #   "t_id in pl_node_map" branch below, or the sig's generic
            #   "else"). Kept for symmetry/robustness with the brief's
            #   request, in case a future topology produces this shape
            #   directly.
            elif t_anc in ("PL", "PR") and node_type_map.get(t_id) == "Valve_5_2_Ways":
                margin = _PL_ANCHOR_MIN_MARGIN if t_anc == "PR" else -_PL_ANCHOR_MIN_MARGIN
                desired_x = tgt_x + margin
                push_dir = -1 if t_anc == "PL" else 1
            elif t_anc in ("A", "B") and node_type_map.get(t_id) == "Valve_5_2_Ways":
                desired_x = tgt_x
                push_dir = 0
            else:
                desired_x = tgt_x
                push_dir = 0
                avoid_global_x = False
            rail.request_tap(s_id, owner_id=owner_id, owner_y=node_pos.get(t_id, (0, 0))[1],
                              desired_x=desired_x, conn_ref=conn, side="source",
                              push_dir=push_dir, avoid_global_x=avoid_global_x)

        elif t_id in pl_node_map and t_anc.startswith("X"):
            src_x = _target_x(s_id, s_anc)
            # Live-UI testing found a real bug: every memory computes the
            # SAME src_x for PL/A/B (the local anchor doesn't depend on
            # WHICH memory, only on the type/anchor), so mem[0].B,
            # mem[1].B, mem[2].B... all targeted the SAME anchor on their
            # respective PLs -- the conflict check (avoid_global_x/
            # same_order) misses this because these connections don't
            # CROSS each other (they keep a consistent order), they just
            # stack in the same column, cutting through other
            # memories'/sigs' bodies along the way.
            if node_type_map.get(s_id) == "Valve_5_2_Ways" and s_id in mc_idx_by_id:
                mem_idx = mc_idx_by_id[s_id]
                next_mem_id = roles["mc_by_idx"].get(mem_idx + 1)
                driving_x = (driving_sig_x_by_mem.get(next_mem_id)
                             if s_anc == "B" and next_mem_id else None)
                if driving_x is not None:
                    # mem[i].B (i != mem[-1], the highest): targets well
                    # to the left of the 3/2 valve that drives mem[i+1]
                    # directly (that confirmation's chain[-1]) -- otherwise
                    # the trace cuts through that valve on its way up
                    # (found via live-UI testing, with an attached drawing
                    # showing the expected route). mem[-1] (with no memory
                    # above it) keeps the generic stagger below.
                    #
                    # Live-UI testing found a real bug (with an annotated
                    # screenshot): the original margin
                    # (v32_width + pilot_w = 400px) kept the trace too far
                    # from the sig, creating a visually large detour
                    # instead of hugging it -- pilot_w alone is already
                    # enough to clear the sig's left actuator
                    # (limit_switch).
                    src_x = driving_x - _M.pilot_w
                else:
                    # Stagger the target per memory, growing rightward
                    # with the index -- each memory ends up targeting its
                    # own column.
                    src_x += mem_idx * _MEM_PL_STAGGER
            # Covers, among others, mem[i].A/mem[i].B -> PL (cascade's
            # ring closure / group bus) -- already generic, no
            # substitution needed (see Task 6 brief, item 2: "a mirrored
            # branch ... needs no change").
            #
            # KNOWN, ACCEPTED FOLLOW-UP RISK (not resolved by this
            # migration): the pre-migration per-memory dedup guard
            # (_mem_pl_used_x) was REMOVED here and is NOT equivalently
            # replaced by RailPlanner's avoid_global_x/same_order check.
            # The old guard's own comment was explicit that avoid_global_x
            # misses exactly the case _mem_pl_used_x existed for: two
            # routes that DON'T cross (same_order is trivially True --
            # they stack in the same column instead of crossing), which
            # was the most common case that guard handled -- see the
            # live-UI bug report cited above (mem[2].B/mem[3].B colliding
            # on the same anchor). No regression has been demonstrated in
            # current tests/probes, so this is not being re-implemented
            # here; it's filed as a known, accepted follow-up risk, same
            # treatment as this plan's own documented follow-ups for
            # _best_pl_anchor_clear_column and _bus_vh_route.
            rail.request_tap(t_id, owner_id=s_id, owner_y=node_pos.get(s_id, (0, 0))[1],
                              desired_x=src_x, conn_ref=conn, side="target",
                              avoid_global_x=True)

    # Turns every registered bus's pending taps into real
    # JunctionNodeItem/PressureLineTerminal nodes + ConnectionItems (see
    # rail.py) -- must run before the OrValve X/Y orientation fix below
    # and before A* routing, since both need the connections list it
    # rewrites (conn["source"/"target"]) to already point at real,
    # positioned nodes. Also appends new nodes to node_by_id/node_pos in
    # place.
    rail.materialize(data, node_by_id, node_pos)
    # node_type_map (built earlier in apply()) is stale after materialize()
    # appends new nodes -- _or_source_x/get_exit_dir/
    # anchor_local_for_routing below need the real type for each of them
    # (PressureLine's "X1"/JunctionNodeItem's "J"/PressureLineTerminal's
    # "X1" entries added to sprite_metrics.py in Task 4).
    node_type_map = {n["id"]: n["type"] for n in data["nodes"]}

    # -- Fixes OrValve X/Y orientation (avoids a crossed wire) --------------
    #
    #   cascade.py connects X to the chronologically earlier source and Y
    #   to the later one (see methods/cascade.py section 6b), without
    #   knowing where each will land in the layout. This works by
    #   coincidence on the PL side (the chronologically farthest source
    #   also ends up physically LEFTMOST, see sign=-1 in leaf_virtual_col
    #   above), but flips on the PR side (the farthest source ends up
    #   physically RIGHTMOST, sign=+1) -- found via live-UI testing (with
    #   an annotated screenshot): on the PR side the rightmost source
    #   entered X (the OrValve's LEFT anchor, exit directions left),
    #   forcing the wire to cross over the entire OrValve to enter from
    #   the wrong side.
    #
    #   X is always the OrValve's LEFT anchor and Y the RIGHT one (see
    #   or_valve.py). Swaps the two ends whenever the source wired to X is
    #   physically to the right of the source wired to Y -- ensures the
    #   leftmost source always enters X and the rightmost enters Y,
    #   regardless of the chronological order cascade.py used to wire
    #   them.
    #
    #   Runs AFTER rail.materialize() (moved here from before the
    #   connections_sorted loop, Task 6 brief): _pl_anchor_x (which used
    #   to compute a PL source's position from its still-indexed "Xi"
    #   anchor name) is gone -- a PL-fed source's connection here only
    #   ever carries a real anchor ("X1" on the PressureLine/
    #   PressureLineTerminal node, or "J" on a JunctionNodeItem tap) once
    #   materialize() has rewritten it, so the generic node_pos-based
    #   lookup below only works post-materialize.
    def _or_source_x(node_id: str, anchor_name: str) -> float | None:
        ntype = node_type_map.get(node_id, "")
        pos = node_by_id.get(node_id, {}).get("position")
        if pos is None:
            return None
        local = anchor_local_for_routing(ntype, anchor_name)
        return pos["x"] + (local[0] if local else 0.0)

    or_xy_conns: dict[str, dict[str, dict]] = {}
    for conn in data["connections"]:
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]
        if node_type_map.get(t_id) == "OrValve" and t_anc in ("X", "Y"):
            or_xy_conns.setdefault(t_id, {})[t_anc] = conn

    for or_id, sides in or_xy_conns.items():
        x_conn, y_conn = sides.get("X"), sides.get("Y")
        if x_conn is None or y_conn is None:
            continue
        x_src_id, y_src_id = x_conn["source"]["node"], y_conn["source"]["node"]
        x_is_or = node_type_map.get(x_src_id) == "OrValve"
        y_is_or = node_type_map.get(y_src_id) == "OrValve"

        if x_is_or or y_is_or:
            # OrValve -> OrValve link (chain of 3+ sources, see
            # methods/cascade.py section 6b: "current" -- always the
            # previous OrValve's accumulator -- always goes to X, "nxt" --
            # always a raw leaf -- always goes to Y). An OrValve's "A"
            # output always exits from the TOP (exit_directions top,
            # or_valve.py), with no "flexible side" like a sig or PL has --
            # comparing against the OTHER input (the heuristic below)
            # isn't enough, because both can be on the SAME side of the
            # target (found via live-UI testing, with an annotated
            # screenshot: the source OrValve, left of the target, still
            # entered from the right). The correct side depends only on
            # the source OrValve's position RELATIVE TO THE TARGET, not on
            # the other input.
            or_src_id = x_src_id if x_is_or else y_src_id
            or_src_x = node_by_id[or_src_id]["position"]["x"]
            target_x = node_by_id[or_id]["position"]["x"]
            wants_x = or_src_x <= target_x
            currently_x = x_is_or
            if wants_x != currently_x:
                x_conn["target"]["anchor"], y_conn["target"]["anchor"] = "Y", "X"
            continue

        x_src_x = _or_source_x(x_src_id, x_conn["source"]["anchor"])
        y_src_x = _or_source_x(y_src_id, y_conn["source"]["anchor"])
        if x_src_x is None or y_src_x is None:
            continue
        if x_src_x > y_src_x:
            x_conn["target"]["anchor"], y_conn["target"]["anchor"] = "Y", "X"

    # -- Children (Exhaust / PressureSource) positioned relative to parent --
    #
    #   Ported verbatim from step_by_step_layout.py (same block).
    _CHILD_ANCHOR = {"Exhaust": "R", "PressureSource": "P"}
    child_parent: dict[str, tuple[str, str]] = {}
    for conn in data["connections"]:
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]
        for child, parent, p_anc in [(s_id, t_id, t_anc), (t_id, s_id, s_anc)]:
            if node_type_map.get(child) in _CHILD_ANCHOR:
                child_parent.setdefault(child, (parent, p_anc))

    gap = cols.get("anchor_child_gap", 32)
    for child_id, (parent_id, parent_anchor) in child_parent.items():
        parent_pos   = node_by_id[parent_id]["position"]
        parent_local = _M.anchor_local.get(node_type_map[parent_id], {}).get(parent_anchor)
        if parent_local is None:
            node_by_id[child_id]["position"] = {"x": parent_pos["x"], "y": parent_pos["y"] + 100}
            continue
        anc_x = parent_pos["x"] + parent_local[0]
        anc_y = parent_pos["y"] + parent_local[1]
        child_type  = node_type_map[child_id]
        child_local = _M.anchor_local.get(child_type, {}).get(_CHILD_ANCHOR[child_type])
        cx = anc_x - (child_local[0] if child_local else 0.0)
        cy = anc_y + gap
        node_by_id[child_id]["position"] = {"x": cx, "y": cy}

    # -- Final cleanup: strip _role from every node --------------------------
    for node in data["nodes"]:
        node.pop("_role", None)

    # -- A* routing -----------------------------------------------------------
    #
    #   Ported verbatim from step_by_step_layout.py (same block).
    from circuit_generator.astar_router import build_grid, route_connection, get_exit_dir

    def _scene_xy(node_id: str, anchor_name: str) -> tuple[float, float] | None:
        pos = node_by_id[node_id]["position"]
        ntype = node_type_map.get(node_id, "")
        local = anchor_local_for_routing(ntype, anchor_name)
        return (pos["x"] + local[0], pos["y"] + local[1]) if local else (pos["x"], pos["y"])

    # A former PL anchor ("Xi") now resolves to a REAL node post-
    # materialize(): the bus's own "PressureLine" node (anchor "X1"), a
    # "PressureLineTerminal" far-end node (anchor "X1"), or an interior
    # "JunctionNodeItem" tap (anchor "J") -- the manual-routing filter
    # below (mem.PL/A/B -> PL) needs to recognize all 3, not just
    # "PressureLine", or it would silently stop matching most of these
    # connections (only the leftmost tap keeps the original PL id) and
    # let A* route them instead.
    _PL_BUS_TYPES = ("PressureLine", "PressureLineTerminal", "JunctionNodeItem")

    # -- Deterministic manual routing: mem.PL/A/B -> PL ----------------------
    #
    #   Live-UI testing: A* can't be trusted for these connections -- even
    #   with the per-memory stagger (above) avoiding two memories
    #   targeting the same anchor, A* could still pick a path that cuts
    #   through another memory/sig along the way, since it only avoids
    #   KNOWN obstacles, not "each memory should get its own lane." Routes
    #   it by hand instead: exit in the source anchor's natural direction
    #   (EXIT_PX stub, like A*), bend to align with the already-chosen
    #   target anchor's column (x), then go straight up to it -- 2 fixed
    #   waypoints, no pathfinding decision involved.
    _EXIT_DIR_VEC = {"UP": (0, -1), "DOWN": (0, 1), "LEFT": (-1, 0), "RIGHT": (1, 0)}
    _MANUAL_EXIT_PX = 40  # same EXIT_PX astar_router uses, for visual consistency

    manually_routed: set[int] = set()
    for i, conn in enumerate(data.get("connections", [])):
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]
        if not (s_anc in ("PL", "A", "B") and node_type_map.get(s_id) == "Valve_5_2_Ways"
                and node_type_map.get(t_id) in _PL_BUS_TYPES):
            continue
        spos = _scene_xy(s_id, s_anc)
        tpos = _scene_xy(t_id, t_anc)
        if spos is None or tpos is None:
            continue
        src_dir = get_exit_dir("Valve_5_2_Ways", s_anc)
        if src_dir in ("LEFT", "RIGHT"):
            # Live-UI testing found a real bug (with an annotated
            # screenshot -- a spurious little "tail"): PL (and PR, if ever
            # used here) already exits positioned OUTSIDE the body on its
            # own (anchor_local_for_routing = -pilot_w/+pilot_w, not right
            # on the edge like B/A) -- adding another EXIT_PX stub could
            # push the point past where the target anchor actually is
            # (which tends to sit closer to the body, because of the
            # stagger), forcing the trace to double back right at the
            # exit. No stub here: goes straight from the source to the
            # target anchor's column -- a SECOND real bug (the same
            # "tail", found again during live-UI testing): since
            # stub == spos in this case, the two waypoints below landed on
            # the exact same point (same x, same y) -- a zero-length
            # segment, rendered as a spurious visual tail right on top of
            # the anchor. A single waypoint (the corner) is enough: the
            # first segment (anchor -> corner) is already the horizontal
            # stretch leaving the source, no need to repeat the starting
            # point as a waypoint.
            corner = (tpos[0], spos[1])
            conn["waypoints"] = [{"x": corner[0], "y": corner[1]}]
            manually_routed.add(i)
            continue
        dx, dy = _EXIT_DIR_VEC[src_dir]
        stub = (spos[0] + dx * _MANUAL_EXIT_PX, spos[1] + dy * _MANUAL_EXIT_PX)
        corner = (tpos[0], stub[1])
        conn["waypoints"] = [{"x": stub[0], "y": stub[1]}, {"x": corner[0], "y": corner[1]}]
        manually_routed.add(i)

    # -- Deterministic manual routing: sig.A -> sig.P (chain links) ---------
    #
    #   Covers both Region A's sig_stack links (same column, see Task 3)
    #   and Region B's confirm_row links (same row, different columns, see
    #   Task 5) and the closure chain (button's column) -- all use the
    #   SAME connection shape (sig.A -> next_sig.P or sig.A -> btn.P,
    #   since btn is also a Valve_3_2_Ways). Live-UI testing: A* can't be
    #   trusted here either -- even the "same column" case (which should
    #   be a simple vertical line) was coming out as a 4-waypoint zigzag.
    #
    #   Same column (A and P share x, the most common case -- sig_stack
    #   and the closure chain): a straight vertical line, no waypoints (A*
    #   doesn't even need to run, the straight segment between the two
    #   anchors is already the right path).
    #   Different columns (confirm_row, when the confirmed atom is a
    #   parallel block): exits A horizontally to the midpoint, moves
    #   up/down to P's height, enters P horizontally -- 2 waypoints,
    #   forming a "Z" (H-V-H) instead of zigzagging.
    for i, conn in enumerate(data.get("connections", [])):
        if i in manually_routed:
            continue
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]
        if not (s_anc == "A" and t_anc == "P"
                and node_type_map.get(s_id) == "Valve_3_2_Ways"
                and node_type_map.get(t_id) == "Valve_3_2_Ways"):
            continue
        spos = _scene_xy(s_id, s_anc)
        tpos = _scene_xy(t_id, t_anc)
        if spos is None or tpos is None:
            continue
        # Detects "same column" from the NODE's position, not the
        # anchor's: "P" always adds the worst-case commutation offset
        # (anchor_local_for_routing, see earlier fix), "A" never adds
        # anything -- comparing spos/tpos directly would make a genuinely
        # same-column sig_stack/closure chain look like a "different
        # column" just because of that offset, triggering the Z
        # unnecessarily.
        same_column = round(node_by_id[s_id]["position"]["x"]) == round(node_by_id[t_id]["position"]["x"])
        if same_column:
            conn["waypoints"] = []
        else:
            mid_x = (spos[0] + tpos[0]) / 2
            conn["waypoints"] = [{"x": mid_x, "y": spos[1]}, {"x": mid_x, "y": tpos[1]}]
        manually_routed.add(i)

    astar_grid = build_grid(data["nodes"])
    for i, conn in enumerate(data.get("connections", [])):
        if i in manually_routed:
            continue
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]
        spos = _scene_xy(s_id, s_anc)
        tpos = _scene_xy(t_id, t_anc)
        if spos is None or tpos is None:
            continue
        s_type, t_type = node_type_map.get(s_id, ""), node_type_map.get(t_id, "")
        wps = route_connection(astar_grid, spos, get_exit_dir(s_type, s_anc),
                                tpos, get_exit_dir(t_type, t_anc),
                                src_type=s_type, tgt_type=t_type,
                                src_id=s_id, tgt_id=t_id)
        if wps is not None:
            conn["waypoints"] = wps

    return data
