"""
Step-by-step (pneumatic) method spatial layout.

Takes the circuit data dict (with _role on each node, generated by
circuit_generator.methods.step_by_step_pneumatic) and fills in x/y
positions for every component using circuit_generator.grid_layout.Grid.

Three vertical regions (see docs/superpowers/specs/
2026-07-11-step-by-step-positioning-design.md):
  1. Piston/valve (cylinder + 4/2 valve), one column per letter.
  2. PressureLines (one per atom), stacked in atom order -- each one IS
     a Grid row (unlike cascade).
  3. Logic (memory + confirmation/relay sig), one column per atom. Valve
     1 (relay) always sits one row below and one column left of Valve 2
     (memory) that it feeds -- including atom 0's block (button +
     closure sig), treated as one more Valve1/Valve2 pair under the same
     rule.

PressureLine anchors (X1, X2, ...) arrive from the topology generator
with arbitrary sequential indices (no notion of screen position) -- this
module REASSIGNS them by real proximity (the X position of the component
on the other side of each connection), with conflict resolution when two
connections compete for the same anchor (same idea as layout_engine.py's
"Phase 3", cascade).
"""

import json
import math

from circuit_generator.grid_layout import Grid
from circuit_generator.sprite_metrics import METRICS as _M, anchor_local_for_routing
from paths import get_base_dir

_CONFIG_PATH = get_base_dir() / "circuit_generator" / "step_by_step_layout_config.json"

# Must match astar_router.route_connection's _OFFSET (entry offset applied
# toward the target anchor) -- a PL anchor chosen closer than this to the
# PR pilot's X produces a tight/ugly path (near-zero jog then re-entry at
# the same offset).
_PL_ANCHOR_MIN_MARGIN = 20

# How many spare anchors global pruning keeps beyond the actually-used
# range (used_min/used_max) on each end of the PressureLine -- gives the
# router maneuvering room past the last real connection, and on the left
# side often removes nothing at all (keeps the full reserve generated by
# step_by_step_pneumatic.py), which is the intent.
_PL_PRUNE_MARGIN = 8


def _build_role_maps(data: dict) -> dict:
    """Extracts the letter/index -> node_id maps from each node's _role."""
    role_map = {n["id"]: n.get("_role", "") for n in data["nodes"]}

    cyl_by_letter: dict[str, str] = {}
    v42_by_letter: dict[str, str] = {}
    pl_by_idx: dict[int, str] = {}
    mc_by_idx: dict[int, str] = {}
    btn_id: str | None = None

    for nid, role in role_map.items():
        if role.startswith("cylinder:"):
            cyl_by_letter[role.split(":", 1)[1]] = nid
        elif role.startswith("main_valve:"):
            v42_by_letter[role.split(":", 1)[1]] = nid
        elif role.startswith("pressure_line_step:"):
            pl_by_idx[int(role.split(":", 1)[1])] = nid
        elif role.startswith("memory:"):
            mc_by_idx[int(role.split(":", 1)[1])] = nid
        elif role == "button":
            btn_id = nid

    return {
        "role_map":     role_map,
        "cyl_by_letter": cyl_by_letter,
        "v42_by_letter": v42_by_letter,
        "pl_by_idx":     pl_by_idx,
        "mc_by_idx":     mc_by_idx,
        "btn_id":        btn_id,
        "n_atoms":       len(mc_by_idx),
    }


def _build_confirmation_chains(data: dict, roles: dict) -> dict[str, list[str]]:
    """Derives, from the connections list, the serial sig chain that
    confirms each transition -- target (memory node_id, or btn_id for
    closure) -> ordered list of sig_ids (1 element if the source atom
    isn't a parallel block, 2+ if it is)."""
    role_map = roles["role_map"]

    sig_out: dict[str, tuple[str, str]] = {}       # sig_id -> (target_id, target_anchor)
    sig_p_from_pl: set[str] = set()                 # sig_ids whose P comes from a PressureLine
    sig_p_from_sig: dict[str, str] = {}              # sig_id -> previous sig_id in the chain
    node_type_map = {n["id"]: n["type"] for n in data["nodes"]}

    for conn in data["connections"]:
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]

        if role_map.get(s_id, "").startswith("signal_valve:") and s_anc == "A":
            sig_out[s_id] = (t_id, t_anc)

        if role_map.get(t_id, "").startswith("signal_valve:") and t_anc == "P":
            if node_type_map.get(s_id) == "PressureLine":
                sig_p_from_pl.add(t_id)
            elif role_map.get(s_id, "").startswith("signal_valve:"):
                sig_p_from_sig[t_id] = s_id

    chains: dict[str, list[str]] = {}
    for head_sig in sig_p_from_pl:
        chain = [head_sig]
        current = head_sig
        while current in sig_out:
            target_id, target_anchor = sig_out[current]
            if role_map.get(target_id, "").startswith("signal_valve:"):
                chain.append(target_id)
                current = target_id
            else:
                chains[target_id] = chain
                break

    return chains


def apply(data: dict) -> dict:
    cfg  = json.loads(_CONFIG_PATH.read_text(encoding="utf-8"))
    cols = cfg["columns"]
    rows = cfg["rows"]

    node_type_map = {n["id"]: n["type"] for n in data["nodes"]}
    roles = _build_role_maps(data)
    node_by_id = {n["id"]: n for n in data["nodes"]}

    grid = Grid()

    # _place_aligned/_reserved_cols defined up here (not only near the
    # logic region, where they originated) because the piston/valve
    # region now also needs a VIRTUAL column index -- see note below.
    _reserved_cols: dict[str, set[int]] = {}

    def _place_aligned(row_id: str, virtual_col: int, node_id: str) -> tuple[float, float]:
        """Like grid.place, but guarantees col_idx == virtual_col by
        reserving earlier columns not yet used in this row with
        placeholder ids -- Grid.place indexes by arrival order, not by
        the column_key value (see grid_layout.py)."""
        reserved = _reserved_cols.setdefault(row_id, set())
        for kk in range(virtual_col):
            if kk not in reserved:
                grid.place(row_id, kk, f"__reserved__{row_id}__{kk}__")
                reserved.add(kk)
        reserved.add(virtual_col)
        return grid.place(row_id, virtual_col, node_id)

    # -- Piston/valve region -------------------------------------------------
    #
    #   Each letter occupies a virtual column computed below (column
    #   reservation per letter/side), not a fixed index -- the space
    #   between consecutive cylinders varies to fit each side's OrValve
    #   chain. cyl_cell_w is the width of ONE column slot.
    cyl_cell_w = cols["group_gap"]
    grid.add_row("cylinder",   cyl_cell_w, _M.cyl_height, rows["cylinder"],
                 x_origin=cols["cylinder_first_x"])
    # NOTE: v42_align_offset_x from config is NOT applied here -- applying it
    # to this row's x_origin (as the brief's Step 4 draft literally showed)
    # makes cylinder and main_valve x positions diverge by that offset,
    # contradicting the brief's own Step 2 test
    # (test_cylinders_and_v42_positioned_same_column_per_letter, which
    # asserts cyl_a.x == v42_a.x). Left in the config for a later task that
    # may need it for a different purpose (e.g. connector/anchor alignment).
    grid.add_row("main_valve", cyl_cell_w, _M.v42_height, rows["main_valve"],
                 x_origin=cols["cylinder_first_x"])

    # Column reservation per letter/side: max(1, number of OrValves on
    # that side) -- each OrValve in a pilot's chain occupies 1 dedicated
    # column (growing only in X, a single row -- see "Position OrValve"
    # below). Each OrValve's _role (f"or_valve:{letter}:{PL|PR}:{i}")
    # already gives the letter and side directly -- no need to re-walk
    # the original event sequence.
    or_nodes = [n for n in data["nodes"] if n["type"] == "OrValve"]
    or_chain_len: dict[tuple[str, str], int] = {}
    for n in or_nodes:
        _, or_letter, or_side, _or_i = n["_role"].split(":")
        key = (or_letter, or_side)
        or_chain_len[key] = or_chain_len.get(key, 0) + 1

    def _pilot_reserve(letter: str, side: str) -> int:
        # NOTE: name deliberately different from the "_reserved_cols" dict
        # already used by _place_aligned (defined at the top of apply())
        # -- reusing the same name here would shadow that dict within
        # this scope and silently break _place_aligned.
        return max(1, or_chain_len.get((letter, side), 0))

    letters = sorted(roles["cyl_by_letter"])
    cyl_col: dict[str, int] = {}
    col = 0
    for letter in letters:
        col += _pilot_reserve(letter, "PL")
        cyl_col[letter] = col
        col += 1 + _pilot_reserve(letter, "PR")

    for letter in letters:
        cyl_id = roles["cyl_by_letter"][letter]
        v42_id = roles["v42_by_letter"][letter]
        x, y = _place_aligned("cylinder", cyl_col[letter], cyl_id)
        node_by_id[cyl_id]["position"] = {"x": x, "y": y}
        x, y = _place_aligned("main_valve", cyl_col[letter], v42_id)
        node_by_id[v42_id]["position"] = {"x": x, "y": y}

    # -- OrValve chain (multi-cycle): its own row, aligned to the same
    # virtual columns as "cylinder"/"main_valve" -----------------------------
    #
    #   The OR CLOSEST to the cylinder must be the LAST in the chain
    #   (whose "A" feeds the 4/2's pilot directly) -- shortest/most
    #   central final wire, raw PL sources farthest away. or_i=0 is the
    #   FIRST one created (merges the first 2 sources), or_i=len-1 is the
    #   LAST (the one feeding the pilot) -- hence the offset is inverted:
    #   (or_chain_len - or_i), not (or_i + 1).
    #   Each OrValve has virtual_col = cyl_col[letter] +/- offset (left
    #   for PL, right for PR) -- can be NEGATIVE (e.g. the first letter,
    #   chain on the left). Grid.place indexes by arrival order, never
    #   negative (same problem already solved for PressureLine anchors,
    #   see "Sizes PressureLines..." below) -- so this row's x_origin is
    #   shifted by the smallest virtual_col used, and _place_aligned
    #   receives (virtual_col - smallest_virtual_col), always >= 0. The
    #   subtraction cancels out exactly with the x_origin shift, so the
    #   real position stays cols["cylinder_first_x"] + virtual_col *
    #   cyl_cell_w -- the SAME formula used by "cylinder"/"main_valve".
    if or_nodes:
        or_virtual_col: dict[str, int] = {}
        for n in or_nodes:
            _, or_letter, or_side, or_i = n["_role"].split(":")
            sign = -1 if or_side == "PL" else 1
            offset = or_chain_len[(or_letter, or_side)] - int(or_i)
            or_virtual_col[n["id"]] = cyl_col[or_letter] + sign * offset

        min_vcol = min(or_virtual_col.values())
        grid.add_row("or_row", cyl_cell_w, _M.or_height, rows["or_row"],
                     x_origin=cols["cylinder_first_x"] + min_vcol * cyl_cell_w)
        # _place_aligned reserves placeholders 0..virtual_col-1 BEFORE
        # placing at virtual_col (see definition above) -- only works if
        # calls within the SAME row arrive in INCREASING virtual_col
        # order. or_nodes' natural order (generation order, increasing i
        # per chain) does NOT guarantee this: on the PL side,
        # vcol = cyl_col[letter] - (i+1) DECREASES as i grows. Without
        # sorting here, a PL chain's second OrValve (smaller vcol) would
        # arrive AFTER the first (larger vcol) and collide with the
        # placeholder the first one already reserved for that column.
        for n in sorted(or_nodes, key=lambda n: or_virtual_col[n["id"]]):
            vcol = or_virtual_col[n["id"]]
            x, y = _place_aligned("or_row", vcol - min_vcol, n["id"])
            node_by_id[n["id"]]["position"] = {"x": x, "y": y}

    # -- PressureLines: one Grid row per atom, stacked -----------------------
    pl_cell_w = 200  # single column per row, value not used for alignment
    for k in sorted(roles["pl_by_idx"]):
        pl_id = roles["pl_by_idx"][k]
        y = rows["pl_base"] + k * rows["pl_gap"]
        grid.add_row(f"pl_row_{k}", pl_cell_w, _M.pl_pix_h, y,
                     x_origin=cols["cylinder_first_x"])
        x, y2 = grid.place(f"pl_row_{k}", 0, pl_id)
        node_by_id[pl_id]["position"] = {"x": x, "y": y2}

    # -- Logic region: memory (Valve 2) + relay (Valve 1) --------------------
    n_atoms       = roles["n_atoms"]
    logic_cell_w  = cols["logic_cell_width"]
    memory_x0     = cols["cylinder_first_x"]
    memory_y      = rows["pl_base"] + n_atoms * rows["pl_gap"] + rows["logic_row_gap"]

    # Doubled VIRTUAL column index (2k for memory, 2k-1 for the relay
    # that feeds it) -- each atom occupies 2 dedicated columns ("M + 2k",
    # see spec), never reusing the previous atom's memory column.
    # _place_aligned (defined above, alongside _reserved_cols) keeps the
    # "memory" row (sparse in virtual-index terms -- only uses the even
    # pairs 0,2,4,...) from hitting Grid's arrival-order problem: without
    # it, atom k's relay would land in atom k-1's memory column.
    grid.add_row("memory", logic_cell_w, _M.v32_height, memory_y, x_origin=memory_x0)
    for k in sorted(roles["mc_by_idx"]):
        mc_id = roles["mc_by_idx"][k]
        x, y = _place_aligned("memory", 2 * k, mc_id)
        node_by_id[mc_id]["position"] = {"x": x, "y": y}

    chains = _build_confirmation_chains(data, roles)

    # NOTE (a second real inconsistency found in the brief's literal
    # text, independent of the one above): Step 3's literal formulas give
    # the "btn_row" row (memory_y + 1*logic_row_gap, column 0 relative to
    # memory_x0) the EXACT same cell that atom 1's relay chain head
    # occupies in the "relay" row (also memory_y + 1*logic_row_gap, and
    # column mc1.x - logic_cell_w == mc0.x == memory_x0 by pure
    # arithmetic -- MC_1 is always exactly 1 cell to the right of MC_0 in
    # the "memory" row, which is dense/gapless). This isn't an
    # implementation artifact: given that
    #   test_relay_sig_one_column_left_of_its_memory requires
    #     sig.x == mc1.x - logic_cell_w  and  sig.y == mc1.y + logic_row_gap
    # and mc1.x - logic_cell_w == mc0.x always, that position ALWAYS
    # collides with "SAME column as MC_0" -- and Step 3's btn_row uses
    # the same row (memory_y + 1*logic_row_gap) as the "relay" row.
    # Confirmed by running the tests with Step 3's literal formulas:
    # gen-btn and atom 1's relay chain head (e.g. gen-sig-A-ext-0) land on
    # the same (x, y) -- in BOTH test sequences, not just the parallel
    # one.
    #
    # The button follows the SAME general diagonal rule as any
    # Valve1/Valve2 pair (1 column left, 1 row below whoever it feeds):
    # it plays the role of MC_0's "Valve 1". The closure chain, in turn,
    # is IN SERIES with the button (not another diagonal pair) -- it sits
    # in the SAME column as the button, 1 row below, exactly like
    # relay_stack_N sits in the same column as the relay it extends.
    #
    # Grid.place indexes columns by ARRIVAL ORDER within the row, not by
    # the column_key value (see grid_layout.py) -- col_idx is never
    # negative (starts at 0 and only grows). _place_aligned works around
    # this by reserving placeholders 0..virtual_col-1 BEFORE placing at
    # virtual_col, but only works for virtual_col >= 0. Since the button
    # needs an effectively NEGATIVE column (left of MC_0, which is
    # already at column 0), we use dedicated rows with x_origin
    # explicitly shifted left, instead of _place_aligned/virtual column.
    btn_id = roles["btn_id"]
    btn_x0 = memory_x0 - logic_cell_w
    grid.add_row("btn_row", logic_cell_w, _M.v32_height,
                 memory_y + rows["logic_row_gap"], x_origin=btn_x0)
    x, y = grid.place("btn_row", 0, btn_id)
    node_by_id[btn_id]["position"] = {"x": x, "y": y}

    # The closure chain is walked back to front when positioning:
    # closure_chain[-1] (whose A feeds btn.P) sits at the top, closest to
    # the button; closure_chain[0] (receives P directly from the last
    # atom's PL) sits at the bottom -- the wire goes down from the PL to
    # the bottommost valve, and confirmation goes up (A -> P) to the
    # last one, which feeds Valve 2 (the button) from above. Same
    # principle for the other atoms' relay, right below.
    closure_chain_top_down = list(reversed(chains[btn_id]))
    grid.add_row("closure_row", logic_cell_w, _M.v32_height,
                 memory_y + 2 * rows["logic_row_gap"], x_origin=btn_x0)
    x, y = grid.place("closure_row", 0, closure_chain_top_down[0])
    node_by_id[closure_chain_top_down[0]]["position"] = {"x": x, "y": y}

    # Closure chain tail (when the last atom is a parallel block, the
    # chain has 2+ sigs in series): same column as closure_row (== the
    # button), stacked 1 logic_row_gap per depth below it -- same pattern
    # as relay_stack_N, but anchored to closure_row.
    for depth, sig_id in enumerate(closure_chain_top_down[1:], start=1):
        stack_row_id = f"closure_stack_{depth}"
        grid.add_row(stack_row_id, logic_cell_w, _M.v32_height,
                     memory_y + 2 * rows["logic_row_gap"] + depth * rows["logic_row_gap"],
                     x_origin=btn_x0)
        x, y = grid.place(stack_row_id, 0, sig_id)
        node_by_id[sig_id]["position"] = {"x": x, "y": y}

    # Relay (Valve 1) for the other atoms: a DEDICATED column (virtual
    # index 2k-1), 1 cell_width left of the memory it feeds (virtual 2k)
    # and 1 cell_width right of the previous atom's memory (virtual
    # 2(k-1) = 2k-2) -- never reuses another block's column. Same
    # x_origin as the "memory" row (no longer shifted by -1 cell_width),
    # since the virtual index alone now guarantees the correct relative
    # position in both directions.
    grid.add_row("relay", logic_cell_w, _M.v32_height,
                 memory_y + rows["logic_row_gap"], x_origin=memory_x0)

    stack_rows_added: set[str] = set()
    for k in sorted(roles["mc_by_idx"]):
        if k == 0:
            continue  # atom 0 already handled above (button block)
        mc_id = roles["mc_by_idx"][k]
        # Walked back to front when positioning -- see the note above,
        # in the button/closure block: whoever feeds mc_id.PL (last in
        # the chain) sits at the top (the "relay" row), whoever receives
        # P directly from the PL (first in the chain) sits at the
        # bottom.
        sig_chain = list(reversed(chains[mc_id]))
        x, y = _place_aligned("relay", 2 * k - 1, sig_chain[0])
        node_by_id[sig_chain[0]]["position"] = {"x": x, "y": y}
        for depth, sig_id in enumerate(sig_chain[1:], start=1):
            stack_row_id = f"relay_stack_{depth}"
            if stack_row_id not in stack_rows_added:
                grid.add_row(stack_row_id, logic_cell_w, _M.v32_height,
                             memory_y + rows["logic_row_gap"] + depth * rows["logic_row_gap"],
                             x_origin=memory_x0)
                stack_rows_added.add(stack_row_id)
            x, y = _place_aligned(stack_row_id, 2 * k - 1, sig_id)
            node_by_id[sig_id]["position"] = {"x": x, "y": y}

    node_pos = {nid: (n["position"]["x"], n["position"]["y"]) for nid, n in node_by_id.items()}
    pl_node_map = {pid: node_by_id[pid] for pid in roles["pl_by_idx"].values()}

    # -- Sizes PressureLines from the grid's real reach -----------------------
    #
    #   step_by_step_pneumatic.py has no real screen position to decide
    #   how many anchors a PressureLine needs -- only this step knows,
    #   via Grid (which has already positioned the whole piston/valve/
    #   logic region above). Grows (never shrinks) each PL's anchor array
    #   to cover, in BOTH directions, the entire circuit's physical reach
    #   -- done once here, BEFORE any connection is resolved, so no
    #   PL -> Valve_3_2_Ways.P connection (see astar_router "PressureLine
    #   -> Valve_3_2_Ways.P", which goes straight down from the anchor)
    #   needs to reactively grow the array on its own -- it only CHOOSES,
    #   among the anchors that already exist, the nearest one to the left
    #   of the valve body + limit-switch actuator (same width as the
    #   pilot: METRICS.pilot_w). Global pruning (further below, already
    #   in place) trims back to the actually-used range + margin, so
    #   overestimating here doesn't leave the final PressureLine bigger
    #   than needed.
    #
    #   Reserving from the grid's GLOBAL min_x/max_x (not a specific
    #   node's) guarantees margin for both the rightmost and leftmost
    #   component of the WHOLE circuit -- not just the target of the
    #   connection in question, which was the problem with an earlier
    #   version of this fix (it only saw its own connection's valve, not
    #   others in the same column, e.g. MC_0/button in the closure
    #   column).
    pl_row_ids = {f"pl_row_{k}" for k in roles["pl_by_idx"]}
    x_range = grid.occupied_x_range(exclude_rows=pl_row_ids)
    if x_range is not None:
        min_x, max_x = x_range
        reach_margin = cols["logic_cell_width"]
        left_margin = _M.pilot_w
        for pl_id, pl_node in pl_node_map.items():
            existing_idxs = [int(a[1:]) for a in pl_node["properties"]["anchors"]]
            needed_max = max(1, math.ceil(
                (max_x + reach_margin - pl_node["position"]["x"] - _M.pl_pix_w / 2) / _M.pl_spacing
            ) + 1)
            needed_min = math.floor(
                (min_x - left_margin - pl_node["position"]["x"] - _M.pl_pix_w / 2) / _M.pl_spacing
            ) + 1
            lo = min(needed_min, min(existing_idxs) if existing_idxs else 1)
            hi = max(needed_max, max(existing_idxs) if existing_idxs else 1)
            pl_node["properties"]["anchors"] = [f"X{i}" for i in range(lo, hi + 1)]
            # PressureLine.layout_anchors() (graphics/items/base/nodes/
            # expandable/pressure_line.py) positions each anchor by its
            # INDEX IN THE LIST (enumerate), not by the number in its
            # "Xi" name -- the two only coincide if the array starts at
            # X1. When reserving anchors to the left (lo < 1), the
            # position must shift to compensate, otherwise ALL named
            # anchors (including ones already chosen by older
            # connections) render shifted RIGHT in the actual scene --
            # same logic already used by global pruning (below), which
            # compensates the opposite case (shrinking instead of
            # growing) the same way.
            if lo < 1:
                pl_node["position"]["x"] += (lo - 1) * _M.pl_spacing
                node_pos[pl_id] = (pl_node["position"]["x"], pl_node["position"]["y"])

    # -- PressureLine anchor reassignment by proximity ------------------------
    #
    #   The topology generator assigns X1, X2, ... sequentially, with no
    #   notion of screen position -- this produces wires that
    #   unnecessarily cross the drawing (the rightmost component can end
    #   up stuck to an anchor far to the left). Reassigns each anchor to
    #   the one nearest the real X position of the component on the
    #   other side of the connection -- same idea as layout_engine.py's
    #   "Phase 3" (cascade), with _pl_anchor_x/_nearest_pl_anchor/
    #   _resolve_conflict copied from there (generic, nothing
    #   Valve_5_2_Ways-specific) and adapted to step-by-step's connection
    #   set (only 4 shapes, far fewer than cascade -- doesn't need the
    #   "free column" logic cascade uses for the sig.P case, because
    #   step-by-step's logic region always sits below every PL, without
    #   the above/below ambiguity that motivates that function there).
    def _pl_anchor_x(pl_node: dict, anchor_name: str, list_origin: int | None = None) -> float:
        # PressureLine.layout_anchors() (graphics/items/base/nodes/
        # expandable/pressure_line.py) positions each anchor by its INDEX
        # IN THE LIST (enumerate(self.anchor_list)), not by the number in
        # its "Xi" name -- the two only coincide if the array is
        # contiguous AND starts at X1. The position.x compensation done
        # in "Sizes PressureLines..." (above) and in global pruning
        # (below) keeps X1 always at the SAME physical x it had before
        # any left-side anchor reservation -- but only works if we use
        # the array's current smallest index as the origin here (instead
        # of the constant 1), reproducing the same shift
        # layout_anchors() actually applies. list_origin can be passed in
        # ready by a caller that already computed it (e.g.
        # _nearest_pl_anchor, which calls this once per anchor --
        # recomputing it here every time would make this scan O(n^2) in
        # the array size).
        pl_x = node_pos[pl_node["id"]][0]
        if list_origin is None:
            list_origin = min(int(a[1:]) for a in pl_node["properties"]["anchors"])
        return pl_x + _M.pl_pix_w / 2 + (int(anchor_name[1:]) - list_origin) * _M.pl_spacing

    def _nearest_pl_anchor(pl_node: dict, target_x: float, side: str = "any",
                            min_margin: float = 0.0) -> str:
        anchors = pl_node["properties"]["anchors"]
        list_origin = min(int(a[1:]) for a in anchors)
        scored = [(int(n[1:]), _pl_anchor_x(pl_node, n, list_origin), n) for n in anchors]
        if side == "left":
            candidates = [(abs(ax - target_x), n) for _, ax, n in scored if ax < target_x - min_margin]
            fallback = sorted(scored)[0][2]
        elif side == "right":
            candidates = [(abs(ax - target_x), n) for _, ax, n in scored if ax > target_x + min_margin]
            fallback = sorted(scored, reverse=True)[0][2]
        else:
            candidates = [(abs(ax - target_x), n) for _, ax, n in scored]
            fallback = anchors[0]
        return min(candidates)[1] if candidates else fallback

    # Keyed by (PressureLine id, rounded x) / (PressureLine id, owner) --
    # not just by the X position or the owner alone. All step-by-step
    # PressureLines share the same x_origin (same X0 column), so the
    # same anchor index (e.g. X8) lands at the SAME screen position on
    # any row -- without the per-PL namespace, a spurious collision
    # between connections on DIFFERENT rows (which don't actually
    # compete for the same anchor) could push a connection on top of one
    # already legitimately registered on ITS OWN row, evaluating the
    # "opposite sides" heuristic with the WRONG row's pl_y.
    pl_anchor_used: dict[tuple[str, int], tuple[str, float, float]] = {}
    conn_by_owner: dict[tuple[str, str], tuple] = {}

    # Keyed only by rounded x (WITHOUT the PL id) -- unlike
    # pl_anchor_used above. Used by connections that go straight down/up
    # between a PL and another component (OrValve.X/Y, sig.P, and the
    # mc.A -> PL ring closure): two DIFFERENT PLs' sources choosing the
    # same X only becomes a real problem when the two wires actually
    # CROSS -- not any repeated X. If the lower source (larger Y)
    # connects to the lower PL (larger YPL) and vice versa, the order is
    # consistent and the traces run parallel without crossing. Only when
    # the order INVERTS (e.g. the lower source targeting the upper PL) do
    # the wires actually cross and need pushing -- same "same_order"
    # criterion already used below for per-PL collisions, applied here
    # across different PLs. Not reused by the PL/PR connections because
    # the note above (about pl_anchor_used) documents a real bug that
    # happened from treating collisions on DIFFERENT rows as if they were
    # on the same row -- here it's deliberate, not a repeat of that
    # mistake.
    or_source_x_used: dict[int, tuple[str, float, float]] = {}

    def _resolve_conflict(pl_node: dict, anchor: str, owner: str,
                           owner_y: float, conn_ref: dict, side: str,
                           push_dir: int = 0, avoid_global_x: bool = False) -> str:
        # push_dir: forced direction to re-push on collision (+1 =
        # always further right, -1 = always further left, 0 = old
        # heuristic based on the row's midpoint). Needed for side-biased
        # cases (PL/PR): without it, a collision would push the anchor
        # back toward the PressureLine's middle, possibly crossing back
        # below the minimum margin (or to the wrong side of the target)
        # -- the "push" needs to keep going in the same direction that
        # motivated the side choice in the first place.
        anchors = pl_node["properties"]["anchors"]
        n, mid = len(anchors), len(anchors) / 2

        def _next(anc: str, direction: int) -> str:
            idx = int(anc[1:])
            step = direction if direction else ((-1) if idx <= mid else 1)
            return f"X{max(1, min(n, idx + step))}"

        pl_y = node_pos.get(pl_node["id"], (0, 0))[1]

        def _reg(anc: str, oid: str, oy: float, cref: dict, seen: set, pdir: int) -> str:
            if anc in seen:
                return anc  # no free slot in that direction -- give up, keep it
            seen = seen | {anc}
            ax = _pl_anchor_x(pl_node, anc)

            if avoid_global_x:
                gx = round(ax)
                prev_global = or_source_x_used.get(gx)
                if prev_global is not None:
                    prev_oid, prev_oy, prev_pl_y = prev_global
                    same_order = (oy < prev_oy) == (pl_y < prev_pl_y)
                    if prev_oid != oid and not same_order:
                        return _reg(_next(anc, pdir), oid, oy, cref, seen, pdir)
                or_source_x_used[gx] = (oid, oy, pl_y)

            key = (pl_node["id"], round(ax))
            owner_key = (pl_node["id"], oid)
            if key not in pl_anchor_used:
                pl_anchor_used[key] = (oid, oy, pl_y)
                conn_by_owner[owner_key] = (cref, side, pl_node, pdir)
                return anc
            prev_id, prev_y, prev_pl_y = pl_anchor_used[key]
            if prev_id == oid:
                return anc
            curr_above = oy < pl_y
            prev_above = prev_y < prev_pl_y
            opp_sides = curr_above != prev_above
            if pl_y != prev_pl_y:
                same_order = (oy < prev_y) == (pl_y < prev_pl_y)
            else:
                same_order = True
            if opp_sides and same_order:
                return anc
            if oy >= prev_y:
                return _reg(_next(anc, pdir), oid, oy, cref, seen, pdir)
            else:
                pl_anchor_used[key] = (oid, oy, pl_y)
                conn_by_owner[owner_key] = (cref, side, pl_node, pdir)
                prev_owner_key = (pl_node["id"], prev_id)
                prev_conn, prev_side, prev_pl, prev_pdir = conn_by_owner.get(
                    prev_owner_key, (None, None, None, 0))
                if prev_conn is not None:
                    new_anc = _reg(_next(anc, prev_pdir), prev_id, prev_y, prev_conn, set(), prev_pdir)
                    prev_conn[prev_side]["anchor"] = new_anc
                return anc

        return _reg(anchor, owner, owner_y, conn_ref, set(), push_dir)

    def _target_x(node_id: str, anchor_name: str) -> float:
        ntype = node_type_map.get(node_id, "")
        pos = node_by_id[node_id]["position"]
        local = anchor_local_for_routing(ntype, anchor_name)
        return pos["x"] + local[0] if local else pos["x"]

    def _conn_sort_key(c: dict) -> tuple:
        t_id = c["target"]["node"]
        return (0, 0) if t_id in pl_node_map else (1, 0)

    connections_sorted = sorted(
        [c for c in data["connections"] if c["source"]["node"] != c["target"]["node"]],
        key=_conn_sort_key,
    )

    for conn in connections_sorted:
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]

        if s_id in pl_node_map and s_anc.startswith("X"):
            pl = pl_node_map[s_id]
            tgt_x = _target_x(t_id, t_anc)
            avoid_global_x = False
            # owner identifies "the other side" of the connection for
            # conflict purposes -- normally t_id (the target node) is
            # already enough, since each node only receives 1 connection
            # per relevant anchor here (PL, PR, P). But an OrValve
            # receives TWO distinct connections (X and Y, both with the
            # same t_id) -- using only t_id, _resolve_conflict treats the
            # second as "same owner, no conflict" (the "if prev_id ==
            # oid: return anc" line) and lets both land on the SAME
            # anchor. Includes the anchor in owner just for this case, to
            # genuinely treat them as DIFFERENT owners.
            owner_id = f"{t_id}#{t_anc}" if node_type_map.get(t_id) == "OrValve" else t_id
            if t_anc == "PL":
                anc = _nearest_pl_anchor(pl, tgt_x, "left")
                push_dir = -1
            elif t_anc == "PR":
                anc = _nearest_pl_anchor(pl, tgt_x, "right", min_margin=_PL_ANCHOR_MIN_MARGIN)
                push_dir = 1
            elif t_anc == "P" and node_type_map.get(t_id) == "Valve_3_2_Ways":
                # The wire goes straight down from this anchor to the
                # valve (see astar_router "PressureLine ->
                # Valve_3_2_Ways.P") -- must stay left of the valve BODY
                # and the limit-switch actuator (same width as the pilot:
                # METRICS.pilot_w), otherwise the trace goes down THROUGH
                # it (or another valve in the same column, e.g. MC_0/
                # button in the closure column). The needed anchors were
                # already created (see "Sizes PressureLines..." above).
                valve_left_x = node_by_id[t_id]["position"]["x"]
                safe_x = valve_left_x - _M.pilot_w
                anc = _nearest_pl_anchor(pl, safe_x, "left")
                push_dir = -1
                # Same global-crossing problem as the OrValve X/Y block
                # below: a PL -> sig.P connection can pick the same X as
                # a PL -> OrValve.X/Y connection from ANOTHER PL, forming
                # one continuous vertical line between the two -- uses
                # the same dict/order criterion.
                avoid_global_x = True
            elif t_anc == "X" and node_type_map.get(t_id) == "OrValve":
                # X is the OrValve's LEFT input (anchor_local fixed at
                # x=0, see sprite_metrics/or_valve.py) -- the PL anchor
                # needs to sit to its left with an exit margin, otherwise
                # the wire goes straight up and needs a sideways jog to
                # enter.
                anc = _nearest_pl_anchor(pl, tgt_x, "left", min_margin=_PL_ANCHOR_MIN_MARGIN)
                push_dir = -1
                avoid_global_x = True
            elif t_anc == "Y" and node_type_map.get(t_id) == "OrValve":
                # Y is the OrValve's RIGHT input -- same idea as X,
                # mirrored.
                anc = _nearest_pl_anchor(pl, tgt_x, "right", min_margin=_PL_ANCHOR_MIN_MARGIN)
                push_dir = 1
                avoid_global_x = True
            else:
                anc = _nearest_pl_anchor(pl, tgt_x)
                push_dir = 0
                avoid_global_x = False
            conn["source"]["anchor"] = _resolve_conflict(
                pl, anc, owner_id, node_pos.get(t_id, (0, 0))[1], conn, "source", push_dir,
                avoid_global_x=avoid_global_x)

        elif t_id in pl_node_map and t_anc.startswith("X"):
            pl = pl_node_map[t_id]
            src_x = _target_x(s_id, s_anc)
            anc = _nearest_pl_anchor(pl, src_x)
            # Same global crossing as the block above (PL as SOURCE,
            # for OrValve/sig.P): a connection with PL as the TARGET
            # (e.g. mc.A -> PL, ring closure) can pick the same X as one
            # of those on ANOTHER row, forming the same misleading
            # continuous vertical line.
            conn["target"]["anchor"] = _resolve_conflict(
                pl, anc, s_id, node_pos.get(s_id, (0, 0))[1], conn, "target",
                avoid_global_x=True)

    # -- Global PressureLine pruning -----------------------------------------
    #
    #   Every PL in the circuit ends up the SAME width (covering from the
    #   circuit's first to last column, with a margin of
    #   _PL_PRUNE_MARGIN anchors on each side) -- same spirit as cascade's
    #   pruning (layout_engine.py's Phase 3.9), which also uses a GLOBAL
    #   range shared across all PLs, not a per-row range (per-row
    #   pruning, tried in an earlier sub-project, produced different
    #   widths between rows -- looked like loose fragments instead of one
    #   continuous bus). Difference from cascade: a margin larger than 1
    #   on each side (confirmed with the user).
    #
    #   Equal final width across all PLs no longer comes from an anchor
    #   budget set at generation time (step_by_step_pneumatic.py today
    #   only places one anchor per real connection touching the row --
    #   different PLs can leave the topology with different counts) --
    #   what guarantees equality now is the "Sizes PressureLines from the
    #   grid's real reach" step (above in this function), which grows
    #   every PL's anchor array to the same `needed`, computed from the
    #   same x_origin (cols["cylinder_first_x"]) and the same global
    #   max_x (Grid.occupied_x_range()) for all of them. This assumes no
    #   PL ever arrives from the topology with more real anchors than
    #   this shared `needed` -- doesn't happen in circuits this generator
    #   produces, and
    #   test_all_pressure_lines_share_the_same_anchor_count
    #   (tests/test_step_by_step_layout.py) guards the invariant.
    used_min, used_max = float("inf"), float("-inf")
    for conn in data["connections"]:
        for side in (conn["source"], conn["target"]):
            if side["node"] in pl_node_map and side["anchor"].startswith("X"):
                idx = int(side["anchor"][1:])
                used_min = min(used_min, idx)
                used_max = max(used_max, idx)

    if used_min != float("inf"):
        for pl_id, pl_node in pl_node_map.items():
            all_idxs = [int(a[1:]) for a in pl_node["properties"]["anchors"]]
            keep_min = max(min(all_idxs), used_min - _PL_PRUNE_MARGIN)
            keep_max = min(max(all_idxs), used_max + _PL_PRUNE_MARGIN)
            pl_node["properties"]["anchors"] = [f"X{i}" for i in all_idxs if keep_min <= i <= keep_max]
            removed_left = keep_min - min(all_idxs)
            pl_node["position"]["x"] += removed_left * _M.pl_spacing
            node_pos[pl_id] = (pl_node["position"]["x"], pl_node["position"]["y"])

    # -- Children (Exhaust / PressureSource) positioned relative to parent --
    _CHILD_ANCHOR = {"Exhaust": "R", "PressureSource": "P"}
    child_parent: dict[str, tuple[str, str]] = {}
    for conn in data["connections"]:
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]
        for child, parent, p_anc in [(s_id, t_id, t_anc), (t_id, s_id, s_anc)]:
            if node_type_map.get(child) in _CHILD_ANCHOR:
                child_parent.setdefault(child, (parent, p_anc))

    gap = cols.get("anchor_child_gap", 32)
    for child_id, (parent_id, parent_anchor) in child_parent.items():
        parent_pos   = node_by_id[parent_id]["position"]
        parent_local = _M.anchor_local.get(node_type_map[parent_id], {}).get(parent_anchor)
        if parent_local is None:
            node_by_id[child_id]["position"] = {"x": parent_pos["x"], "y": parent_pos["y"] + 100}
            continue
        anc_x = parent_pos["x"] + parent_local[0]
        anc_y = parent_pos["y"] + parent_local[1]
        child_type  = node_type_map[child_id]
        child_local = _M.anchor_local.get(child_type, {}).get(_CHILD_ANCHOR[child_type])
        cx = anc_x - (child_local[0] if child_local else 0.0)
        cy = anc_y + gap
        node_by_id[child_id]["position"] = {"x": cx, "y": cy}

    # -- Final cleanup: strip _role from every node --------------------------
    for node in data["nodes"]:
        node.pop("_role", None)

    # -- A* routing -----------------------------------------------------------
    from circuit_generator.astar_router import build_grid, route_connection, get_exit_dir

    def _scene_xy(node_id: str, anchor_name: str,
                  peer_type: str | None = None) -> tuple[float, float] | None:
        pos = node_by_id[node_id]["position"]
        ntype = node_type_map.get(node_id, "")
        if ntype == "PressureLine" and anchor_name.startswith("X"):
            idx = int(anchor_name[1:])
            # PressureLine.layout_anchors() (graphics/items/base/nodes/
            # expandable/pressure_line.py) positions each anchor at
            # y0=self.pix_h -- pl_pix_h below the node's position, not at
            # the position itself. Without adding this, routing thinks
            # the anchor is pl_pix_h higher than it's actually rendered,
            # and the connection crosses back over it.
            #
            # X has the same caveat as _pl_anchor_x (above):
            # layout_anchors() positions by INDEX IN THE LIST, not by the
            # number in the name -- uses the array's current smallest
            # index as the origin, not the constant 1, otherwise the
            # waypoint computed here won't match where the anchor is
            # actually drawn whenever the PL reserved anchors to the
            # left.
            list_origin = min(int(a[1:]) for a in node_by_id[node_id]["properties"]["anchors"])
            return (pos["x"] + _M.pl_pix_w / 2 + (idx - list_origin) * _M.pl_spacing, pos["y"] + _M.pl_pix_h)
        local = anchor_local_for_routing(ntype, anchor_name, peer_type=peer_type)
        return (pos["x"] + local[0], pos["y"] + local[1]) if local else (pos["x"], pos["y"])

    astar_grid = build_grid(data["nodes"])
    for conn in data.get("connections", []):
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]
        s_type, t_type = node_type_map.get(s_id, ""), node_type_map.get(t_id, "")
        spos = _scene_xy(s_id, s_anc, peer_type=t_type or None)
        tpos = _scene_xy(t_id, t_anc, peer_type=s_type or None)
        if spos is None or tpos is None:
            continue
        wps = route_connection(astar_grid, spos, get_exit_dir(s_type, s_anc),
                                tpos, get_exit_dir(t_type, t_anc),
                                src_type=s_type, tgt_type=t_type,
                                src_id=s_id, tgt_id=t_id)
        if wps is not None:
            conn["waypoints"] = wps

    return data
