"""
Step-by-step (electric) method spatial layout.

Takes the circuit data dict (with _role on each node, generated by
circuit_generator.methods.step_by_step_electric) and fills in x/y
positions for every component using circuit_generator.grid_layout.Grid.

v1 -- see docs/superpowers/specs/2026-07-30-step-by-step-electric-layout-design.md,
docs/superpowers/specs/2026-07-31-step-by-step-electric-power-contacts-design.md
and docs/superpowers/specs/2026-07-31-step-by-step-electric-layout-v1-design.md.

Unlike v0: each atom is now one COHESIVE BLOCK (ramo A | ramo B at the
top, converging into reset+K coil right below, all in the same column
band) -- no longer two distant zones (ramo A/B on one end, reset+K on
the other). The power zone (Y), though, still stays grouped separately,
to the right of every atom block -- that's the part matching "reset+coil
all sits together at the end" from the original brainstorm (initially
misread as being about the K block, corrected after seeing v0 rendered).

Vertical bands (top -> bottom):
  1. Piston/valve (cylinder + 4/2 valve), one column per letter.
  2. VoltageSource (horizontal bar).
  3. Cohesive block per atom: ramo A (col 3k) | ramo B (col 3k+1) | button
     (col 3k+2, last atom only) -- reset (NC) and K coil stacked right
     below, in the SAME column as ramo B (3k+1).
     Power zone (to the RIGHT of every atom block, same Y band): 1
     sub-column per (cylinder, direction) present -- power contact(s)
     stacked above the matching Y coil.
  4. Ground (horizontal bar).

Anchor reassignment by proximity (NEW in v1, v0 left this out of scope):
since there's only ONE VoltageSource and ONE Ground (not one per atom,
like the pneumatic method's PressureLine), the assignment is simpler
than step_by_step_layout.py's "Phase 3" -- sorts each bus's connections
by the real X position of the component on the other side and matches
them 1:1 with anchors sorted by X, guaranteeing zero crossings by
construction (monotonic mapping), with no need for push-based conflict
resolution.
"""

from circuit_generator.grid_layout import Grid
from circuit_generator.rail import RailPlanner
from circuit_generator.sprite_metrics import METRICS as _M, anchor_local_for_routing


def _build_role_maps(data: dict) -> dict:
    role_map = {n["id"]: n.get("_role", "") for n in data["nodes"]}

    cyl_by_letter: dict[str, str] = {}
    v42_by_letter: dict[str, str] = {}
    coil_by_idx: dict[int, str] = {}
    contact_by_role: dict[str, str] = {}
    power_coil_by_group: dict[tuple[str, str], str] = {}
    vsource_id: str | None = None
    ground_id: str | None = None
    btn_id: str | None = None
    btn_start_id: str | None = None

    for nid, role in role_map.items():
        if role.startswith("cylinder:"):
            cyl_by_letter[role.split(":", 1)[1]] = nid
        elif role.startswith("main_valve:"):
            v42_by_letter[role.split(":", 1)[1]] = nid
        elif role.startswith("power_coil:"):
            _, letter, direction = role.split(":")
            dir_tag = "ext" if direction == "+" else "ret"
            power_coil_by_group[(letter, dir_tag)] = nid
        elif role.startswith("coil:"):
            coil_by_idx[int(role.split(":", 1)[1])] = nid
        elif role.startswith("contact:"):
            contact_by_role[role.split(":", 1)[1]] = nid
        elif role == "voltage_source":
            vsource_id = nid
        elif role == "ground":
            ground_id = nid
        elif role == "button":
            btn_id = nid
        elif role == "button_start":
            btn_start_id = nid

    power_contacts_by_group: dict[tuple[str, str], list[tuple[int, str]]] = {}
    for role_key, nid in contact_by_role.items():
        if role_key.startswith("power-"):
            _, letter, dir_tag, k_str = role_key.split("-")
            power_contacts_by_group.setdefault((letter, dir_tag), []).append((int(k_str), nid))

    return {
        "role_map":                role_map,
        "cyl_by_letter":           cyl_by_letter,
        "v42_by_letter":           v42_by_letter,
        "coil_by_idx":             coil_by_idx,
        "contact_by_role":         contact_by_role,
        "power_coil_by_group":     power_coil_by_group,
        "power_contacts_by_group": power_contacts_by_group,
        "vsource_id":              vsource_id,
        "ground_id":               ground_id,
        "btn_id":                  btn_id,
        "btn_start_id":            btn_start_id,
        "n_atoms":                 len(coil_by_idx),
    }


def apply(data: dict) -> dict:
    node_type_map = {n["id"]: n["type"] for n in data["nodes"]}
    node_by_id = {n["id"]: n for n in data["nodes"]}
    roles = _build_role_maps(data)
    n_atoms = roles["n_atoms"]

    grid = Grid()
    _reserved_cols: dict[str, set[int]] = {}

    def _place_aligned(row_id: str, virtual_col: int, node_id: str) -> tuple[float, float]:
        reserved = _reserved_cols.setdefault(row_id, set())
        for kk in range(virtual_col):
            if kk not in reserved:
                grid.place(row_id, kk, f"__reserved__{row_id}__{kk}__")
                reserved.add(kk)
        reserved.add(virtual_col)
        return grid.place(row_id, virtual_col, node_id)

    # -- Config (v1: hardcoded, no external json file) -----------------------
    #
    #   cyl_cell_w bumped to 1000 (was 300) -- explicit user request after
    #   seeing v0 rendered ("space between the pistons, like 1000px").
    #
    #   vsource_row_y/ramo_row_y/ramo_stack_gap: v0 had a real collision
    #   here -- vsource_row_y (700) coincided EXACTLY with the first
    #   stacked sensor row. A later fix pinned ramo_row_y to a constant
    #   (1700) large enough for the defensive WORST CASE (depth up to 5),
    #   but that left the circuit artificially tall for any shallower
    #   sequence (e.g. "A+B+A-B-", depth 1, left ~750px of empty gap).
    #   ramo_row_y is now computed from the circuit's REAL MAXIMUM depth
    #   (max_stack_above = the largest sensor stack across all atoms),
    #   always guaranteeing exactly 1 level of clearance
    #   (ramo_stack_gap) between the stack's deepest level and the
    #   VoltageSource's base -- no more, no less:
    #     ramo_row_y = vsource_row_y + vsource_pix_h + (max_stack_above+1)*ramo_stack_gap
    #   Reproduces the old values exactly when max_stack_above=5 (gave
    #   1700), but grows/shrinks with each sequence's real depth.
    #
    #   The cycle-start button (gen-btn-start, atom 0 only) enters as
    #   just one more stacked level on this SAME grid, 1 ramo_stack_gap
    #   below ramo_row (instead of its own row at an arbitrary fraction
    #   between ramo_row and reset_row) -- electrically it's already
    #   just one more series contact in ramo A, so visually it should
    #   also just be one more step of the same stack.
    cyl_cell_w = 1000
    cyl_first_x = 0.0
    cyl_row_y = 0.0
    v42_row_y = 400.0
    vsource_row_y = 700.0
    ramo_stack_gap = 150.0
    reset_gap = 150.0
    coil_gap = 150.0
    ground_gap = 300.0
    zone_gap = 400.0
    ramo_cell_w = 200.0
    zone3_cell_w = 200.0

    contact_by_role = roles["contact_by_role"]
    sensor_depth_by_atom = {
        k: sum(1 for role_key in contact_by_role if role_key.startswith(f"{k}-ramo_a_sensor"))
        for k in range(n_atoms)
    }
    max_stack_above = max(sensor_depth_by_atom.values(), default=0)

    ramo_row_y = vsource_row_y + _M.vsource_pix_h + (max_stack_above + 1) * ramo_stack_gap
    start_btn_row_y = ramo_row_y + ramo_stack_gap
    reset_row_y = start_btn_row_y + reset_gap
    coil_row_y = reset_row_y + coil_gap
    ground_row_y = coil_row_y + ground_gap

    # -- Piston/valve region -- no OrValve/pilot_sig in the electric
    #    generator, so always 1 column per letter ---------------------------
    letters = sorted(roles["cyl_by_letter"])
    cyl_col: dict[str, int] = {letter: i for i, letter in enumerate(letters)}

    grid.add_row("cylinder", cyl_cell_w, _M.cyl_height, cyl_row_y, x_origin=cyl_first_x)
    grid.add_row("main_valve", cyl_cell_w, _M.v42_height, v42_row_y, x_origin=cyl_first_x)

    for letter in letters:
        cyl_id = roles["cyl_by_letter"][letter]
        v42_id = roles["v42_by_letter"][letter]
        x, y = grid.place("cylinder", cyl_col[letter], cyl_id)
        node_by_id[cyl_id]["position"] = {"x": x, "y": y}
        x, y = grid.place("main_valve", cyl_col[letter], v42_id)
        node_by_id[v42_id]["position"] = {"x": x, "y": y}

    # -- VoltageSource (horizontal bar, top of the electric band) ---------
    vsource_id = roles["vsource_id"]
    node_by_id[vsource_id]["position"] = {"x": cyl_first_x, "y": vsource_row_y}

    # -- Cohesive block per atom: ramo A | ramo B (top) + reset/K coil
    #    (right below, same column as ramo B) -------------------------------
    grid.add_row("ramo_row", ramo_cell_w, _M.contact_height, ramo_row_y,
                 x_origin=cyl_first_x)
    # Cycle-start button: in series at the end of the FIRST atom's ramo A
    # -- same column as ramo A (0), 1 level below ramo_row on the same
    # grid as the sensors (where it sits electrically: after the previous
    # K's contact, before converging with ramo B).
    grid.add_row("start_btn_row", ramo_cell_w, _M.contact_height, start_btn_row_y,
                 x_origin=cyl_first_x)
    grid.add_row("reset_row", ramo_cell_w, _M.contact_height, reset_row_y,
                 x_origin=cyl_first_x)
    grid.add_row("coil_row", ramo_cell_w, _M.relay_coil_height, coil_row_y,
                 x_origin=cyl_first_x)

    def _contact(role_key: str) -> str:
        return contact_by_role[role_key]

    stack_rows_added: set[str] = set()
    for k in range(n_atoms):
        # Ramo A: sensor-contact chain (i=0,1,...) + the previous K's contact.
        sensor_roles = sorted(
            k2 for k2 in contact_by_role if k2.startswith(f"{k}-ramo_a_sensor")
        )
        prev_role = f"{k}-ramo_a_prev"
        prev_id = _contact(prev_role)
        x, y = _place_aligned("ramo_row", 3 * k, prev_id)
        node_by_id[prev_id]["position"] = {"x": x, "y": y}
        for depth, sensor_role in enumerate(reversed(sensor_roles), start=1):
            sensor_id = _contact(sensor_role)
            stack_row_id = f"ramo_a_stack_{depth}"
            if stack_row_id not in stack_rows_added:
                grid.add_row(stack_row_id, ramo_cell_w, _M.contact_height,
                             ramo_row_y - depth * ramo_stack_gap, x_origin=cyl_first_x)
                stack_rows_added.add(stack_row_id)
            x, y = _place_aligned(stack_row_id, 3 * k, sensor_id)
            node_by_id[sensor_id]["position"] = {"x": x, "y": y}

        # Cycle-start button: first atom only.
        if k == 0:
            btn_start_id = roles["btn_start_id"]
            x, y = _place_aligned("start_btn_row", 0, btn_start_id)
            node_by_id[btn_start_id]["position"] = {"x": x, "y": y}

        # Ramo B: K_k's own self-hold.
        self_id = _contact(f"{k}-ramo_b_self")
        x, y = _place_aligned("ramo_row", 3 * k + 1, self_id)
        node_by_id[self_id]["position"] = {"x": x, "y": y}

        # Bootstrap button: last atom only.
        if k == n_atoms - 1:
            btn_id = roles["btn_id"]
            x, y = _place_aligned("ramo_row", 3 * k + 2, btn_id)
            node_by_id[btn_id]["position"] = {"x": x, "y": y}

        # Reset (NC) + K coil: same column as ramo B (3k+1), right below --
        # a cohesive block per atom, no longer a distant zone.
        reset_id = _contact(f"{k}-reset_nc")
        x, y = _place_aligned("reset_row", 3 * k + 1, reset_id)
        node_by_id[reset_id]["position"] = {"x": x, "y": y}

        coil_id = roles["coil_by_idx"][k]
        x, y = _place_aligned("coil_row", 3 * k + 1, coil_id)
        node_by_id[coil_id]["position"] = {"x": x, "y": y}

    # -- Power zone: contacts + Y coil, grouped to the RIGHT of every atom
    #    block -- 1 sub-column per (cylinder, direction) present in the
    #    sequence, ordered by the first atom that triggers that move -----
    power_contacts_by_group = roles["power_contacts_by_group"]
    power_coil_by_group = roles["power_coil_by_group"]

    group_keys = sorted(
        power_contacts_by_group.keys(),
        key=lambda gk: min(k for k, _ in power_contacts_by_group[gk]),
    )

    zone_cols = 3 * (n_atoms - 1) + 3  # last used column + 1 (0-indexed)
    zone3_x0 = cyl_first_x + zone_cols * ramo_cell_w + zone_gap

    power_stack_rows_added: set[str] = set()
    for g, group_key in enumerate(group_keys):
        contacts = sorted(power_contacts_by_group[group_key])  # sort by k
        for depth, (_k, contact_id) in enumerate(contacts, start=1):
            row_id = f"power_row_{depth}"
            if row_id not in power_stack_rows_added:
                grid.add_row(row_id, zone3_cell_w, _M.contact_height,
                             reset_row_y - depth * ramo_stack_gap, x_origin=zone3_x0)
                power_stack_rows_added.add(row_id)
            if depth == 1:
                x, y = grid.place(row_id, g, contact_id)
            else:
                x, y = _place_aligned(row_id, g, contact_id)
            node_by_id[contact_id]["position"] = {"x": x, "y": y}

        coil_id = power_coil_by_group[group_key]
        if "power_coil_row" not in power_stack_rows_added:
            grid.add_row("power_coil_row", zone3_cell_w, _M.solenoid_coil_height,
                         coil_row_y, x_origin=zone3_x0)
            power_stack_rows_added.add("power_coil_row")
        x, y = grid.place("power_coil_row", g, coil_id)
        node_by_id[coil_id]["position"] = {"x": x, "y": y}

    # -- Ground (horizontal bar, bottom of the electric band) -------------
    ground_id = roles["ground_id"]
    node_by_id[ground_id]["position"] = {"x": cyl_first_x, "y": ground_row_y}

    # -- Registers the VoltageSource/Ground bars with RailPlanner, sized
    #    from the grid's real reach (grows, never shrinks -- see
    #    step_by_step_layout.py) -------------------------------------------
    rail = RailPlanner(min_spacing=_M.pl_spacing)
    x_range = grid.occupied_x_range()
    if x_range is not None:
        min_x, max_x = x_range
        needed_span = max(_M.pl_spacing, max_x - min_x)
    else:
        needed_span = _M.pl_spacing
    for bus_id in (vsource_id, ground_id):
        pos = node_by_id[bus_id]["position"]
        width = _M.vsource_pix_w if node_type_map[bus_id] == "VoltageSource" else _M.ground_pix_w * 0.5
        x0 = pos["x"] + width
        rail.register_bus(bus_id, "JunctionNodeItem", y=pos["y"], x_min=x0, x_max=x0 + needed_span)

    # -- Children (Exhaust / PressureSource) positioned relative to parent -
    _CHILD_ANCHOR = {"Exhaust": "R", "PressureSource": "P"}
    child_parent: dict[str, tuple[str, str]] = {}
    for conn in data["connections"]:
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]
        for child, parent, p_anc in [(s_id, t_id, t_anc), (t_id, s_id, s_anc)]:
            if node_type_map.get(child) in _CHILD_ANCHOR:
                child_parent.setdefault(child, (parent, p_anc))

    gap = 32
    for child_id, (parent_id, parent_anchor) in child_parent.items():
        parent_pos = node_by_id[parent_id]["position"]
        parent_local = anchor_local_for_routing(node_type_map[parent_id], parent_anchor)
        if parent_local is None:
            node_by_id[child_id]["position"] = {"x": parent_pos["x"], "y": parent_pos["y"] + 100}
            continue
        anc_x = parent_pos["x"] + parent_local[0]
        anc_y = parent_pos["y"] + parent_local[1]
        child_type = node_type_map[child_id]
        child_local = _M.anchor_local.get(child_type, {}).get(_CHILD_ANCHOR[child_type])
        cx = anc_x - (child_local[0] if child_local else 0.0)
        cy = anc_y + gap
        node_by_id[child_id]["position"] = {"x": cx, "y": cy}

    # -- Anchor reassignment by proximity (VoltageSource/Ground) ------------
    #
    #   The generator assigns X1, X2, ... sequentially, with no notion of
    #   screen position -- this produced unnecessarily crossed wires (the
    #   power zone, far to the right, stuck to an anchor too early in the
    #   array). There's only ONE VoltageSource and ONE Ground (not one
    #   per atom, like the pneumatic method's PressureLine), so the
    #   assignment is a simple monotonic mapping: sorts each bus's
    #   connections by the real X position of the component on the other
    #   side, sorts the anchors by X position, matches them 1:1 --
    #   guarantees ZERO crossings among the bus's own connections by
    #   construction (two connections never swap relative order), with
    #   no need for the push-based conflict logic PressureLine needs
    #   (there, N rows compete for the same X space; here it's a single
    #   bar).
    def _other_endpoint_x(node_id: str, anchor_name: str) -> float:
        pos = node_by_id[node_id]["position"]
        local = anchor_local_for_routing(node_type_map.get(node_id, ""), anchor_name)
        return pos["x"] + (local[0] if local else 0.0)

    vsource_conns = [c for c in data["connections"] if c["source"]["node"] == vsource_id]
    ground_conns = [c for c in data["connections"] if c["target"]["node"] == ground_id]

    # Tracked by identity (not by node id) BEFORE rail.materialize() rewrites
    # each conn_ref's node/anchor in place -- after materialize(), only the
    # tap at bus.x_min still targets the original VoltageSource/Ground node
    # id (interior taps and the x_max tap all get rewritten to point at a
    # new JunctionNodeItem instead). _bus_vh_route's dispatch (below) needs
    # this set to keep recognizing every one of these connections as
    # bus-touching, since the post-materialize node-type check alone would
    # only catch that single x_min tap.
    bus_conn_ids = {id(c) for c in vsource_conns} | {id(c) for c in ground_conns}

    rail.assign_sorted(vsource_id, [
        (c["target"]["node"], node_by_id[c["target"]["node"]]["position"]["y"],
         _other_endpoint_x(c["target"]["node"], c["target"]["anchor"]), c, "source")
        for c in vsource_conns
    ])
    rail.assign_sorted(ground_id, [
        (c["source"]["node"], node_by_id[c["source"]["node"]]["position"]["y"],
         _other_endpoint_x(c["source"]["node"], c["source"]["anchor"]), c, "target")
        for c in ground_conns
    ])

    node_pos = {n["id"]: (n["position"]["x"], n["position"]["y"]) for n in data["nodes"]}
    rail.materialize(data, node_by_id, node_pos)
    node_type_map = {n["id"]: n["type"] for n in data["nodes"]}  # rail added new nodes

    # -- Final cleanup: strip _role from every node -----------------------
    for node in data["nodes"]:
        node.pop("_role", None)

    # -- A* routing (identical to the pneumatic method) --------------------
    from circuit_generator.astar_router import build_grid, route_connection, get_exit_dir

    def _scene_xy(node_id: str, anchor_name: str) -> tuple[float, float] | None:
        pos = node_by_id[node_id]["position"]
        ntype = node_type_map.get(node_id, "")
        local = anchor_local_for_routing(ntype, anchor_name)
        return (pos["x"] + local[0], pos["y"] + local[1]) if local else (pos["x"], pos["y"])

    def _bus_vh_route(spos, tpos):
        """Deterministic VH routing for connections touching VoltageSource/Ground.

        Replaces A* for this case -- the source and the bus always
        exchange vertically (the source always exits from below, ground
        always enters from above, and everything connecting to them
        also faces vertically: T always up, B always down), so the path
        is always straight or, at most, one horizontal jog in the
        middle (VHV) -- never needs to avoid anything, since there's no
        sprite between the bus and the ring's lines below it. Avoids
        the "step" A* produced because of the exit-point snap near the
        bus sprite's own blocking rectangle.
        """
        sx, sy = spos
        tx, ty = tpos
        if abs(sx - tx) < 0.5 or abs(sy - ty) < 0.5:
            return None
        mid_y = (sy + ty) / 2
        return [
            {"x": round(sx, 1), "y": round(mid_y, 1)},
            {"x": round(tx, 1), "y": round(mid_y, 1)},
        ]

    astar_grid = build_grid(data["nodes"])
    for conn in data.get("connections", []):
        s_id, s_anc = conn["source"]["node"], conn["source"]["anchor"]
        t_id, t_anc = conn["target"]["node"], conn["target"]["anchor"]
        spos = _scene_xy(s_id, s_anc)
        tpos = _scene_xy(t_id, t_anc)
        if spos is None or tpos is None:
            continue
        s_type, t_type = node_type_map.get(s_id, ""), node_type_map.get(t_id, "")
        # id(conn) in bus_conn_ids: catches connections that USED to target
        # the VoltageSource/Ground node directly before rail.materialize()
        # rewrote them onto an interior JunctionNodeItem tap (only the
        # bus.x_min tap still has the original bus node id, so the plain
        # type check below would otherwise miss every other bus connection).
        if (id(conn) in bus_conn_ids
                or s_type in ("VoltageSource", "Ground") or t_type in ("VoltageSource", "Ground")):
            wps = _bus_vh_route(spos, tpos)
        else:
            wps = route_connection(astar_grid, spos, get_exit_dir(s_type, s_anc),
                                    tpos, get_exit_dir(t_type, t_anc),
                                    src_type=s_type, tgt_type=t_type,
                                    src_id=s_id, tgt_id=t_id)
        if wps is not None:
            conn["waypoints"] = wps

    return data
